package cobranza.entidad;
// Generated 23/07/2015 09:19:54 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idempresa;
     private String nombre;
     private String direccion;
     private String telefono;
     private String celular;
     private String ciudad;
     private Date fechareg;
     private Set ventas = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public Empresa(int idempresa, String nombre, String direccion, String telefono, String celular, String ciudad, Date fechareg, Set ventas) {
       this.idempresa = idempresa;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.ciudad = ciudad;
       this.fechareg = fechareg;
       this.ventas = ventas;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


