package cobranza.entidad;
// Generated 23/07/2015 09:19:54 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MenuTipoanexo generated by hbm2java
 */
public class MenuTipoanexo  implements java.io.Serializable {


     private int idmenutipo;
     private Menu menu;
     private TipoAnexo tipoAnexo;
     private Date fechareg;

    public MenuTipoanexo() {
    }

	
    public MenuTipoanexo(int idmenutipo, Menu menu, TipoAnexo tipoAnexo) {
        this.idmenutipo = idmenutipo;
        this.menu = menu;
        this.tipoAnexo = tipoAnexo;
    }
    public MenuTipoanexo(int idmenutipo, Menu menu, TipoAnexo tipoAnexo, Date fechareg) {
       this.idmenutipo = idmenutipo;
       this.menu = menu;
       this.tipoAnexo = tipoAnexo;
       this.fechareg = fechareg;
    }
   
    public int getIdmenutipo() {
        return this.idmenutipo;
    }
    
    public void setIdmenutipo(int idmenutipo) {
        this.idmenutipo = idmenutipo;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public TipoAnexo getTipoAnexo() {
        return this.tipoAnexo;
    }
    
    public void setTipoAnexo(TipoAnexo tipoAnexo) {
        this.tipoAnexo = tipoAnexo;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }




}


