package cobranza.entidad;
// Generated 23/07/2015 09:19:54 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Anexo anexo;
     private String usuario;
     private String clave;
     private byte[] fechareg;

    public Usuario() {
    }

	
    public Usuario(int idusuario, Anexo anexo) {
        this.idusuario = idusuario;
        this.anexo = anexo;
    }
    public Usuario(int idusuario, Anexo anexo, String usuario, String clave, byte[] fechareg) {
       this.idusuario = idusuario;
       this.anexo = anexo;
       this.usuario = usuario;
       this.clave = clave;
       this.fechareg = fechareg;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public byte[] getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(byte[] fechareg) {
        this.fechareg = fechareg;
    }




}


