package cobranza.entidad;
// Generated 23/07/2015 09:19:54 AM by Hibernate Tools 4.3.1



/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private VentaId id;
     private Anexo anexo;
     private Empresa empresa;
     private Pago pago;
     private Vehiculo vehiculo;
     private byte[] fechareg;

    public Venta() {
    }

    public Venta(VentaId id, Anexo anexo, Empresa empresa, Pago pago, Vehiculo vehiculo, byte[] fechareg) {
       this.id = id;
       this.anexo = anexo;
       this.empresa = empresa;
       this.pago = pago;
       this.vehiculo = vehiculo;
       this.fechareg = fechareg;
    }
   
    public VentaId getId() {
        return this.id;
    }
    
    public void setId(VentaId id) {
        this.id = id;
    }
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public byte[] getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(byte[] fechareg) {
        this.fechareg = fechareg;
    }




}


