package Model;
// Generated 03/09/2015 09:53:02 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Anexodatcredaval generated by hbm2java
 */
@Entity
@Table(name="anexodatcredaval"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Anexodatcredaval  implements java.io.Serializable {


     private int iddetcredito;
     private Anexo anexo;
     private Integer iddatoscredito;
     private Date fecreg;
     private Set creditos = new HashSet(0);

    public Anexodatcredaval() {
    }

	
    public Anexodatcredaval(int iddetcredito) {
        this.iddetcredito = iddetcredito;
    }
    public Anexodatcredaval(int iddetcredito, Anexo anexo, Integer iddatoscredito, Date fecreg, Set creditos) {
       this.iddetcredito = iddetcredito;
       this.anexo = anexo;
       this.iddatoscredito = iddatoscredito;
       this.fecreg = fecreg;
       this.creditos = creditos;
    }
   
     @Id 

    
    @Column(name="iddetcredito", unique=true, nullable=false)
    public int getIddetcredito() {
        return this.iddetcredito;
    }
    
    public void setIddetcredito(int iddetcredito) {
        this.iddetcredito = iddetcredito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idanexo")
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

    
    @Column(name="iddatoscredito")
    public Integer getIddatoscredito() {
        return this.iddatoscredito;
    }
    
    public void setIddatoscredito(Integer iddatoscredito) {
        this.iddatoscredito = iddatoscredito;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecreg", length=23)
    public Date getFecreg() {
        return this.fecreg;
    }
    
    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="anexodatcredaval")
    public Set getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }




}


