package Model;
// Generated 31/08/2015 11:12:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Anexodatcredaval generated by hbm2java
 */
@Entity
@Table(name="anexodatcredaval"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Anexodatcredaval  implements java.io.Serializable {


     private int iddetcredito;
     private Anexo anexo;
     private Datoscredito datoscredito;
     private Date fecreg;

    public Anexodatcredaval() {
    }

	
    public Anexodatcredaval(int iddetcredito) {
        this.iddetcredito = iddetcredito;
    }
    public Anexodatcredaval(int iddetcredito, Anexo anexo, Datoscredito datoscredito, Date fecreg) {
       this.iddetcredito = iddetcredito;
       this.anexo = anexo;
       this.datoscredito = datoscredito;
       this.fecreg = fecreg;
    }
   
     @Id 

    
    @Column(name="iddetcredito", unique=true, nullable=false)
    public int getIddetcredito() {
        return this.iddetcredito;
    }
    
    public void setIddetcredito(int iddetcredito) {
        this.iddetcredito = iddetcredito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idanexo")
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddatoscredito")
    public Datoscredito getDatoscredito() {
        return this.datoscredito;
    }
    
    public void setDatoscredito(Datoscredito datoscredito) {
        this.datoscredito = datoscredito;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecreg", length=23)
    public Date getFecreg() {
        return this.fecreg;
    }
    
    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }




}


