package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name = "articulo",
         schema = "dbo",
         catalog = "cobranzas"
)
public class Articulo implements java.io.Serializable {

    private Integer idarticulo;
    private Familia familia;
    private Subfamilia subfamilia;
    private Modelo modelo;
    private Tipoarticulo tipoarticulo;
    private Integer consecutivo;
    private String codigo;
    private String descripcion1;
    private String descripcion2;
    private BigDecimal preciocompra;
    private BigDecimal precioventa;
    private BigDecimal costopromedio;
    private String unidadmedida;
    private Integer cantidad;
    private Date created;
    private Set operaciondetalles = new HashSet(0);

    public Articulo() {
    }

    public Articulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }

    public Articulo(Integer idarticulo, Familia familia, Subfamilia subfamilia, Modelo modelo, Tipoarticulo tipoarticulo, Integer consecutivo, String codigo, String descripcion1, String descripcion2, BigDecimal preciocompra, BigDecimal precioventa, BigDecimal costopromedio, String unidadmedida, Integer cantidad, Date created, Set operaciondetalles) {
        this.idarticulo = idarticulo;
        this.familia = familia;
        this.subfamilia = subfamilia;
        this.modelo = modelo;
        this.tipoarticulo = tipoarticulo;
        this.consecutivo = consecutivo;
        this.codigo = codigo;
        this.descripcion1 = descripcion1;
        this.descripcion2 = descripcion2;
        this.preciocompra = preciocompra;
        this.precioventa = precioventa;
        this.costopromedio = costopromedio;
        this.unidadmedida = unidadmedida;
        this.cantidad = cantidad;
        this.created = created;
        this.operaciondetalles = operaciondetalles;
    }

    @Id

    @Column(name = "idarticulo", unique = true, nullable = false)
    public Integer getIdarticulo() {
        return this.idarticulo;
    }

    public void setIdarticulo(Integer idarticulo) {
        this.idarticulo = idarticulo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idfamilia")
    public Familia getFamilia() {
        return this.familia;
    }

    public void setFamilia(Familia familia) {
        this.familia = familia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idsubfamilia")
    public Subfamilia getSubfamilia() {
        return this.subfamilia;
    }

    public void setSubfamilia(Subfamilia subfamilia) {
        this.subfamilia = subfamilia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idmodelo")
    public Modelo getModelo() {
        return this.modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idtipoarticulo")
    public Tipoarticulo getTipoarticulo() {
        return this.tipoarticulo;
    }

    public void setTipoarticulo(Tipoarticulo tipoarticulo) {
        this.tipoarticulo = tipoarticulo;
    }

    @Column(name = "consecutivo")
    public Integer getConsecutivo() {
        return this.consecutivo;
    }

    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }

    @Column(name = "codigo", length = 10)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "descripcion1", length = 100)
    public String getDescripcion1() {
        return this.descripcion1;
    }

    public void setDescripcion1(String descripcion1) {
        this.descripcion1 = descripcion1;
    }

    @Column(name = "descripcion2", length = 100)
    public String getDescripcion2() {
        return this.descripcion2;
    }

    public void setDescripcion2(String descripcion2) {
        this.descripcion2 = descripcion2;
    }

    @Column(name = "preciocompra", precision = 18)
    public BigDecimal getPreciocompra() {
        return this.preciocompra;
    }

    public void setPreciocompra(BigDecimal preciocompra) {
        this.preciocompra = preciocompra;
    }

    @Column(name = "precioventa", precision = 18)
    public BigDecimal getPrecioventa() {
        return this.precioventa;
    }

    public void setPrecioventa(BigDecimal precioventa) {
        this.precioventa = precioventa;
    }

    @Column(name = "costopromedio", precision = 18)
    public BigDecimal getCostopromedio() {
        return this.costopromedio;
    }

    public void setCostopromedio(BigDecimal costopromedio) {
        this.costopromedio = costopromedio;
    }

    @Column(name = "unidadmedida", length = 50)
    public String getUnidadmedida() {
        return this.unidadmedida;
    }

    public void setUnidadmedida(String unidadmedida) {
        this.unidadmedida = unidadmedida;
    }

    @Column(name = "cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", length = 23)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo")
    public Set getOperaciondetalles() {
        return this.operaciondetalles;
    }

    public void setOperaciondetalles(Set operaciondetalles) {
        this.operaciondetalles = operaciondetalles;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idarticulo != null)
                ? idarticulo.equals(((Articulo) other).idarticulo)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idarticulo != null)
                ? (getClass().hashCode() + idarticulo.hashCode())
                : super.hashCode();
    }

}
