package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caja generated by hbm2java
 */
@Entity
@Table(name = "caja",
        schema = "dbo",
        catalog = "cobranzas"
)
public class Caja implements java.io.Serializable {

    private Integer idcaja;
    private String descripcion;
    private Anexo encargado;
    private BigDecimal total;
    private String tienda;
    private String empresa;
    private Set pagoses = new HashSet(0);
    private Set movcajas = new HashSet(0);

    public Caja() {
    }

    public Caja(Integer idcaja) {
        this.idcaja = idcaja;
    }

    public Caja(Integer idcaja, String descripcion, String empresa, Anexo encargado, BigDecimal total, String tienda, Set pagoses, Set movcajas) {
        this.idcaja = idcaja;
        this.descripcion = descripcion;
        this.encargado = encargado;
        this.empresa = empresa;
        this.total = total;
        this.tienda = tienda;
        this.pagoses = pagoses;
        this.movcajas = movcajas;
    }

    @Id

    @Column(name = "idcaja", unique = true, nullable = false)
    public Integer getIdcaja() {
        return this.idcaja;
    }

    public void setIdcaja(Integer idcaja) {
        this.idcaja = idcaja;
    }

    @Column(name = "descripcion", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "empresa", length = 2)
    public String getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    @Column(name = "encargado")
    public Anexo getEncargado() {
        return this.encargado;
    }

    public void setEncargado(Anexo encargado) {
        this.encargado = encargado;
    }

    @Column(name = "total", precision = 17)
    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    @Column(name = "tienda", length = 2)
    public String getTienda() {
        return this.tienda;
    }

    public void setTienda(String tienda) {
        this.tienda = tienda;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
    public Set getPagoses() {
        return this.pagoses;
    }

    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
    public Set getMovcajas() {
        return this.movcajas;
    }

    public void setMovcajas(Set movcajas) {
        this.movcajas = movcajas;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idcaja != null)
                ? idcaja.equals(((Caja) other).idcaja)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idcaja != null)
                ? (getClass().hashCode() + idcaja.hashCode())
                : super.hashCode();
    }

}
