package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "caja", schema = "dbo", catalog = "cobranzas"
)
public class Caja implements java.io.Serializable {

    private Integer idcaja;    
    private String descripcion;
    private Anexo encargado;
    private BigDecimal total;
    private String tienda;
    private Set movcajas = new HashSet(0);

    public Caja() {
    }

    public Caja(Integer idcaja) {
        this.idcaja = idcaja;
    }

    public Caja(Integer idcaja, String descripcion, Anexo encargado, BigDecimal total, String tienda, Set movcajas) {
        this.idcaja = idcaja;        
        this.descripcion = descripcion;
        this.encargado = encargado;
        this.total = total;
        this.tienda = tienda;
        this.movcajas = movcajas;
    }

    @Id

    @Column(name = "idcaja", unique = true, nullable = false)
    public Integer getIdcaja() {
        return this.idcaja;
    }

    public void setIdcaja(Integer idcaja) {
        this.idcaja = idcaja;
    }        
    
    @Column(name = "descripcion", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }        
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "encargado", nullable = false)
    public Anexo getEncargado() {
        return this.encargado;
    }

    public void setEncargado(Anexo encargado) {
        this.encargado = encargado;
    }
    
    @Column(name = "total", nullable = false, precision = 17)
    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    
    @Column(name = "tienda", length = 2)
    public String getTienda() {
        return this.tienda;
    }

    public void setTienda(String tienda) {
        this.tienda = tienda;
    }
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
    public Set getMovcajas() {
        return this.movcajas;
    }

    public void setMovcajas(Set movcajas) {
        this.movcajas = movcajas;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idcaja != null)
                ? idcaja.equals(((Caja) other).idcaja)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idcaja != null)
                ? (getClass().hashCode() + idcaja.hashCode())
                : super.hashCode();
    }

}

