package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clasificacion generated by hbm2java
 */
@Entity
@Table(name="clasificacion"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Clasificacion  implements java.io.Serializable {


     private int id;
     private String clasificacion;
     private String descripcion;

    public Clasificacion() {
    }

	
    public Clasificacion(int id) {
        this.id = id;
    }
    public Clasificacion(int id, String clasificacion, String descripcion) {
       this.id = id;
       this.clasificacion = clasificacion;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="clasificacion", length=50)
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


