package Model;
// Generated 21/08/2015 05:10:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Condicionpago generated by hbm2java
 */
@Entity
@Table(name="condicionpago"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Condicionpago  implements java.io.Serializable {


     private Integer idcondicionpago;
     private String nombre;
     private Date fechareg;
     private Set ventas = new HashSet(0);

    public Condicionpago() {
    }

	
    public Condicionpago(Integer idcondicionpago) {
        this.idcondicionpago = idcondicionpago;
    }
    public Condicionpago(Integer idcondicionpago, String nombre, Date fechareg, Set ventas) {
       this.idcondicionpago = idcondicionpago;
       this.nombre = nombre;
       this.fechareg = fechareg;
       this.ventas = ventas;
    }
   
     @Id 

    
    @Column(name="idcondicionpago", unique=true, nullable=false)
    public Integer getIdcondicionpago() {
        return this.idcondicionpago;
    }
    
    public void setIdcondicionpago(Integer idcondicionpago) {
        this.idcondicionpago = idcondicionpago;
    }

    
    @Column(name="nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechareg", length=23)
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="condicionpago")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idcondicionpago != null)
            ? idcondicionpago.equals(((Condicionpago) other).idcondicionpago)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (idcondicionpago != null) 
            ? (getClass().hashCode() + idcondicionpago.hashCode())
            : super.hashCode();
    }


}


