package Model;
// Generated 03/09/2015 09:53:02 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Credito generated by hbm2java
 */
@Entity
@Table(name="credito"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Credito  implements java.io.Serializable {


     private int idventa;
     private Anexo anexoByCodven;
     private Anexo anexoByVerificado;
     private Anexo anexoByIdanexo;
     private Anexodatcredaval anexodatcredaval;
     private Vehiculo vehiculo;
     private String liqventa;
     private String condicionpago;
     private Integer nletras;
     private Date fechareg;
     private String aprobadox;
     private String tienda;
     private String empresa;
     private BigDecimal precio;
     private BigDecimal inicial;
     private BigDecimal saldo;
     private BigDecimal interes;
     private Boolean cronograma;
     private Boolean contrato;
     private Set letrases = new HashSet(0);

    public Credito() {
    }

	
    public Credito(int idventa, Anexo anexoByCodven, Anexo anexoByIdanexo, Vehiculo vehiculo, String liqventa, String condicionpago, Date fechareg, BigDecimal precio) {
        this.idventa = idventa;
        this.anexoByCodven = anexoByCodven;
        this.anexoByIdanexo = anexoByIdanexo;
        this.vehiculo = vehiculo;
        this.liqventa = liqventa;
        this.condicionpago = condicionpago;
        this.fechareg = fechareg;
        this.precio = precio;
    }
    public Credito(int idventa, Anexo anexoByCodven, Anexo anexoByVerificado, Anexo anexoByIdanexo, Anexodatcredaval anexodatcredaval, Vehiculo vehiculo, String liqventa, String condicionpago, Integer nletras, Date fechareg, String aprobadox, String tienda, String empresa, BigDecimal precio, BigDecimal inicial, BigDecimal saldo, BigDecimal interes, Boolean cronograma, Boolean contrato, Set letrases) {
       this.idventa = idventa;       
       this.anexoByCodven = anexoByCodven;
       this.anexoByVerificado = anexoByVerificado;
       this.anexoByIdanexo = anexoByIdanexo;
       this.anexodatcredaval = anexodatcredaval;
       this.vehiculo = vehiculo;
       this.liqventa = liqventa;
       this.condicionpago = condicionpago;
       this.nletras = nletras;
       this.fechareg = fechareg;
       this.aprobadox = aprobadox;
       this.tienda = tienda;
       this.empresa = empresa;
       this.precio = precio;
       this.inicial = inicial;
       this.saldo = saldo;
       this.interes = interes;
       this.cronograma = cronograma;
       this.contrato = contrato;
       this.letrases = letrases;
    }
   
     @Id 

    
    @Column(name="idventa", unique=true, nullable=false)
    public int getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codven", nullable=false)
    public Anexo getAnexoByCodven() {
        return this.anexoByCodven;
    }
    
    public void setAnexoByCodven(Anexo anexoByCodven) {
        this.anexoByCodven = anexoByCodven;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="verificado")
    public Anexo getAnexoByVerificado() {
        return this.anexoByVerificado;
    }
    
    public void setAnexoByVerificado(Anexo anexoByVerificado) {
        this.anexoByVerificado = anexoByVerificado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idanexo", nullable=false)
    public Anexo getAnexoByIdanexo() {
        return this.anexoByIdanexo;
    }
    
    public void setAnexoByIdanexo(Anexo anexoByIdanexo) {
        this.anexoByIdanexo = anexoByIdanexo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idavalcredito")
    public Anexodatcredaval getAnexodatcredaval() {
        return this.anexodatcredaval;
    }
    
    public void setAnexodatcredaval(Anexodatcredaval anexodatcredaval) {
        this.anexodatcredaval = anexodatcredaval;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="liqventa", nullable=false, length=10)
    public String getLiqventa() {
        return this.liqventa;
    }
    
    public void setLiqventa(String liqventa) {
        this.liqventa = liqventa;
    }

    
    @Column(name="condicionpago", nullable=false, length=2)
    public String getCondicionpago() {
        return this.condicionpago;
    }
    
    public void setCondicionpago(String condicionpago) {
        this.condicionpago = condicionpago;
    }

    
    @Column(name="nletras")
    public Integer getNletras() {
        return this.nletras;
    }
    
    public void setNletras(Integer nletras) {
        this.nletras = nletras;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechareg", nullable=false, length=23)
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

    
    @Column(name="aprobadox", length=10)
    public String getAprobadox() {
        return this.aprobadox;
    }
    
    public void setAprobadox(String aprobadox) {
        this.aprobadox = aprobadox;
    }

    
    @Column(name="tienda", length=2)
    public String getTienda() {
        return this.tienda;
    }
    
    public void setTienda(String tienda) {
        this.tienda = tienda;
    }

    
    @Column(name="empresa", length=2)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="precio", nullable=false, precision=17, scale=5)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="inicial", precision=17, scale=5)
    public BigDecimal getInicial() {
        return this.inicial;
    }
    
    public void setInicial(BigDecimal inicial) {
        this.inicial = inicial;
    }

    
    @Column(name="saldo", precision=17, scale=5)
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="interes", precision=17, scale=5)
    public BigDecimal getInteres() {
        return this.interes;
    }
    
    public void setInteres(BigDecimal interes) {
        this.interes = interes;
    }

    
    @Column(name="cronograma")
    public Boolean getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Boolean cronograma) {
        this.cronograma = cronograma;
    }

    
    @Column(name="contrato")
    public Boolean getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Boolean contrato) {
        this.contrato = contrato;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="credito")
    public Set getLetrases() {
        return this.letrases;
    }
    
    public void setLetrases(Set letrases) {
        this.letrases = letrases;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Credito other = (Credito) obj;
        if (this.idventa != other.idventa) {
            return false;
        }
        return true;
    }
}