package Model;
// Generated 03/09/2015 12:09:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Credito generated by hbm2java
 */
@Entity
@Table(name = "credito", schema = "dbo", catalog = "cobranzas"
)
public class Credito implements java.io.Serializable {

    private Integer idventa;
    private Anexo anexoByIdaval;
    private Anexo anexoByCodven;
    private Anexo anexoByVerificado;
    private Anexo anexoByIdanexo;
    private Vehiculo vehiculo;
    private Modelo modelo;
    private String liqventa;
    private String condicionpago;
    private Integer nletras;
    private Date fechareg;
    private String aprobadox;
    private String tienda;
    private String empresa;
    private BigDecimal precio;
    private BigDecimal inicial;
    private BigDecimal saldo;
    private BigDecimal totaldeuda;
    private BigDecimal interes;
    private Boolean cronograma;
    private Boolean contrato;
    private String estado;
    private String vehi;
    private Set letrases = new HashSet(0);

    public Credito() {
    }

    public Credito(Integer idventa, Anexo anexoByCodven, Anexo anexoByIdanexo, Vehiculo vehiculo, String liqventa, String condicionpago, Date fechareg, BigDecimal precio) {
        this.idventa = idventa;
        this.anexoByCodven = anexoByCodven;
        this.anexoByIdanexo = anexoByIdanexo;
        this.vehiculo = vehiculo;
        this.liqventa = liqventa;
        this.condicionpago = condicionpago;
        this.fechareg = fechareg;
        this.precio = precio;
    }

    public Credito(Integer idventa, Anexo anexoByIdaval, Anexo anexoByCodven, Anexo anexoByVerificado, Anexo anexoByIdanexo, Vehiculo vehiculo, Modelo modelo, String liqventa, String condicionpago, Integer nletras, Date fechareg, String aprobadox, String tienda, String empresa, BigDecimal precio, BigDecimal inicial, BigDecimal saldo, BigDecimal totaldeuda, BigDecimal interes, Boolean cronograma, Boolean contrato, Set letrases, String estado, String vehi) {
        this.idventa = idventa;
        this.anexoByIdaval = anexoByIdaval;
        this.anexoByCodven = anexoByCodven;
        this.anexoByVerificado = anexoByVerificado;
        this.anexoByIdanexo = anexoByIdanexo;
        this.vehiculo = vehiculo;
        this.modelo = modelo;
        this.liqventa = liqventa;
        this.condicionpago = condicionpago;
        this.nletras = nletras;
        this.fechareg = fechareg;
        this.aprobadox = aprobadox;
        this.tienda = tienda;
        this.empresa = empresa;
        this.precio = precio;
        this.inicial = inicial;
        this.saldo = saldo;
        this.totaldeuda = totaldeuda;
        this.interes = interes;
        this.cronograma = cronograma;
        this.contrato = contrato;
        this.estado = estado;
        this.vehi = vehi;
        this.letrases = letrases;
    }

    @Id

    @Column(name = "idventa", unique = true, nullable = false)
    public Integer getIdventa() {
        return this.idventa;
    }

    public void setIdventa(Integer idventa) {
        this.idventa = idventa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idaval")
    public Anexo getAnexoByIdaval() {
        return this.anexoByIdaval;
    }

    public void setAnexoByIdaval(Anexo anexoByIdaval) {
        this.anexoByIdaval = anexoByIdaval;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "codven", nullable = false)
    public Anexo getAnexoByCodven() {
        return this.anexoByCodven;
    }

    public void setAnexoByCodven(Anexo anexoByCodven) {
        this.anexoByCodven = anexoByCodven;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "verificado")
    public Anexo getAnexoByVerificado() {
        return this.anexoByVerificado;
    }

    public void setAnexoByVerificado(Anexo anexoByVerificado) {
        this.anexoByVerificado = anexoByVerificado;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idanexo", nullable = false)
    public Anexo getAnexoByIdanexo() {
        return this.anexoByIdanexo;
    }

    public void setAnexoByIdanexo(Anexo anexoByIdanexo) {
        this.anexoByIdanexo = anexoByIdanexo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idvehiculo", nullable = false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }

    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idmodelo", nullable = false)
    public Modelo getModelo() {
        return this.modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    @Column(name = "liqventa", nullable = false, length = 10)
    public String getLiqventa() {
        return this.liqventa;
    }

    public void setLiqventa(String liqventa) {
        this.liqventa = liqventa;
    }

    @Column(name = "condicionpago", nullable = false, length = 2)
    public String getCondicionpago() {
        return this.condicionpago;
    }

    public void setCondicionpago(String condicionpago) {
        this.condicionpago = condicionpago;
    }

    @Column(name = "nletras")
    public Integer getNletras() {
        return this.nletras;
    }

    public void setNletras(Integer nletras) {
        this.nletras = nletras;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechareg", nullable = false, length = 23)
    public Date getFechareg() {
        return this.fechareg;
    }

    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

    @Column(name = "aprobadox", length = 10)
    public String getAprobadox() {
        return this.aprobadox;
    }

    public void setAprobadox(String aprobadox) {
        this.aprobadox = aprobadox;
    }

    @Column(name = "tienda", length = 2)
    public String getTienda() {
        return this.tienda;
    }

    public void setTienda(String tienda) {
        this.tienda = tienda;
    }

    @Column(name = "empresa", length = 2)
    public String getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    @Column(name = "precio", nullable = false, precision = 17, scale = 2)
    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    @Column(name = "inicial", precision = 17, scale = 2)
    public BigDecimal getInicial() {
        return this.inicial;
    }

    public void setInicial(BigDecimal inicial) {
        this.inicial = inicial;
    }

    @Column(name = "saldo", precision = 17, scale = 2)
    public BigDecimal getSaldo() {
        return this.saldo;
    }

    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    
    @Column(name = "totaldeuda", precision = 17, scale = 2)
    public BigDecimal getTotaldeuda() {
        return this.totaldeuda;
    }

    public void setTotaldeuda(BigDecimal totaldeuda) {
        this.totaldeuda = totaldeuda;
    }

    @Column(name = "interes", precision = 17, scale = 2)
    public BigDecimal getInteres() {
        return this.interes;
    }

    public void setInteres(BigDecimal interes) {
        this.interes = interes;
    }

    @Column(name = "cronograma")
    public Boolean getCronograma() {
        return this.cronograma;
    }

    public void setCronograma(Boolean cronograma) {
        this.cronograma = cronograma;
    }

    @Column(name = "contrato")
    public Boolean getContrato() {
        return this.contrato;
    }

    public void setContrato(Boolean contrato) {
        this.contrato = contrato;
    }
    
    @Column(name = "estado", nullable = false, length = 2)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name = "vehi", length = 3)
    public String getVehi() {
        return this.vehi;
    }

    public void setVehi(String vehi) {
        this.vehi = vehi;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "credito")
    public Set getLetrases() {
        return this.letrases;
    }

    public void setLetrases(Set letrases) {
        this.letrases = letrases;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idventa != null)
                ? idventa.equals(((Credito) other).idventa)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idventa != null)
                ? (getClass().hashCode() + idventa.hashCode())
                : super.hashCode();
    }
}
