package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Creditogestor generated by hbm2java
 */
@Entity
@Table(name="creditogestor"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Creditogestor  implements java.io.Serializable {


     private int idcreditogestor;
     private Anexo anexo;
     private Credito credito;
     private Date fecreg;

    public Creditogestor() {
    }

	
    public Creditogestor(int idcreditogestor) {
        this.idcreditogestor = idcreditogestor;
    }
    public Creditogestor(int idcreditogestor, Anexo anexo, Credito credito, Date fecreg) {
       this.idcreditogestor = idcreditogestor;
       this.anexo = anexo;
       this.credito = credito;
       this.fecreg = fecreg;
    }
   
     @Id 

    
    @Column(name="idcreditogestor", unique=true, nullable=false)
    public int getIdcreditogestor() {
        return this.idcreditogestor;
    }
    
    public void setIdcreditogestor(int idcreditogestor) {
        this.idcreditogestor = idcreditogestor;
    }

    
    @Column(name="idanexo")
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

    
    @Column(name="idventa")
    public Credito getCredito() {
        return this.credito;
    }
    
    public void setCredito(Credito credito) {
        this.credito = credito;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecreg", length=23)
    public Date getFecreg() {
        return this.fecreg;
    }
    
    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 11 * hash + this.idcreditogestor;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Creditogestor other = (Creditogestor) obj;
        if (this.idcreditogestor != other.idcreditogestor) {
            return false;
        }
        return true;
    }




}


