package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "detalleventa", schema = "dbo", catalog = "cobranzas"
)
public class Detalleventa implements java.io.Serializable {

    private Integer iddetalleventa;
    private Servicio servicio;
    private Repuesto repuesto;

    public Detalleventa() {
    }

    public Detalleventa(Integer iddetalleventa) {
        this.iddetalleventa = iddetalleventa;
    }

    public Detalleventa(Integer iddetalleventa, Servicio servicio, Repuesto repuesto) {
        this.iddetalleventa = iddetalleventa;
        this.servicio = servicio;
        this.repuesto = repuesto;
    }

    @Id

    @Column(name = "iddetalleventa", unique = true, nullable = false)
    public Integer getIddetalleventa() {
        return this.iddetalleventa;
    }

    public void setIddetalleventa(Integer iddetalleventa) {
        this.iddetalleventa = iddetalleventa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idservicio", nullable = false)
    public Servicio getServicio() {
        return this.servicio;
    }

    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idrepuesto", nullable = false)
    public Repuesto getRepuesto() {
        return this.repuesto;
    }

    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && iddetalleventa != null)
                ? iddetalleventa.equals(((Detalleventa) other).iddetalleventa)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (iddetalleventa != null)
                ? (getClass().hashCode() + iddetalleventa.hashCode())
                : super.hashCode();
    }

}
