package Model;
// Generated 21/08/2015 05:10:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detcredito generated by hbm2java
 */
@Entity
@Table(name="detcredito"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Detcredito  implements java.io.Serializable {


     private Integer iddetcredito;
     private Anexo anexo;
     private Datoscredito datoscredito;
     private Date fecreg;

    public Detcredito() {
    }

	
    public Detcredito(Integer iddetcredito) {
        this.iddetcredito = iddetcredito;
    }
    public Detcredito(Integer iddetcredito, Anexo anexo, Datoscredito datoscredito, Date fecreg) {
       this.iddetcredito = iddetcredito;
       this.anexo = anexo;
       this.datoscredito = datoscredito;
       this.fecreg = fecreg;
    }
   
     @Id 

    
    @Column(name="iddetcredito", unique=true, nullable=false)
    public Integer getIddetcredito() {
        return this.iddetcredito;
    }
    
    public void setIddetcredito(Integer iddetcredito) {
        this.iddetcredito = iddetcredito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idanexo")
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddatoscredito")
    public Datoscredito getDatoscredito() {
        return this.datoscredito;
    }
    
    public void setDatoscredito(Datoscredito datoscredito) {
        this.datoscredito = datoscredito;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecreg", length=23)
    public Date getFecreg() {
        return this.fecreg;
    }
    
    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && iddetcredito != null)
            ? iddetcredito.equals(((Detcredito) other).iddetcredito)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (iddetcredito != null) 
            ? (getClass().hashCode() + iddetcredito.hashCode())
            : super.hashCode();
    }


}


