package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name = "distrito",
         schema = "dbo",
         catalog = "cobranzas"
)
public class Distrito implements java.io.Serializable {

    private Integer iddistrito;
    private String distrito;
    private String abrev;
    private Date fechreg;
    private Set anexos = new HashSet(0);

    public Distrito() {
    }

    public Distrito(Integer iddistrito) {
        this.iddistrito = iddistrito;
    }

    public Distrito(Integer iddistrito, String distrito, String abrev, Date fechreg, Set anexos) {
        this.iddistrito = iddistrito;
        this.distrito = distrito;
        this.abrev = abrev;
        this.fechreg = fechreg;
        this.anexos = anexos;
    }

    @Id

    @Column(name = "iddistrito", unique = true, nullable = false)
    public Integer getIddistrito() {
        return this.iddistrito;
    }

    public void setIddistrito(Integer iddistrito) {
        this.iddistrito = iddistrito;
    }

    @Column(name = "distrito", nullable = false, length = 50)
    public String getDistrito() {
        return this.distrito;
    }

    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    @Column(name = "abrev", length = 50)
    public String getAbrev() {
        return this.abrev;
    }

    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechreg", length = 23)
    public Date getFechreg() {
        return this.fechreg;
    }

    public void setFechreg(Date fechreg) {
        this.fechreg = fechreg;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "distrito")
    public Set getAnexos() {
        return this.anexos;
    }

    public void setAnexos(Set anexos) {
        this.anexos = anexos;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && iddistrito != null)
                ? iddistrito.equals(((Distrito) other).iddistrito)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (iddistrito != null)
                ? (getClass().hashCode() + iddistrito.hashCode())
                : super.hashCode();
    }

}
