package Model;
// Generated 03/09/2015 12:09:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Letras generated by hbm2java
 */
@Entity
@Table(name = "letras", schema = "dbo", catalog = "cobranzas"
)
public class Letras implements java.io.Serializable {

    private Integer idletras;
    private Credito credito;
    private BigDecimal montoletra;
    private Date fecini;
    private Date fecven;
    private BigDecimal monto;
    private BigDecimal interes;    
    private BigDecimal saldo;
    private Date fecreg;
    private String estado;
    private String descripcion;
    private BigDecimal mora;
    private Set pagoses = new HashSet(0);
    private long diffdays;

    public Letras() {
    }

    public Letras(Integer idletras) {
        this.idletras = idletras;
    }

    public Letras(Integer idletras, Credito credito, BigDecimal montoletra, Date fecini, Date fecven, BigDecimal monto, BigDecimal interes, BigDecimal saldo, Date fecreg, String estado,BigDecimal mora, String descripcion, Set pagoses) {
        this.idletras = idletras;
        this.credito = credito;
        this.montoletra = montoletra;
        this.fecini = fecini;
        this.fecven = fecven;
        this.monto = monto;
        this.interes = interes;        
        this.saldo = saldo;
        this.fecreg = fecreg;
        this.estado = estado;
        this.mora = mora;
        this.descripcion = descripcion;
        this.pagoses = pagoses;
    }

    @Id

    @Column(name = "idletras", unique = true, nullable = false)
    public Integer getIdletras() {
        return this.idletras;
    }

    public void setIdletras(Integer idletras) {
        this.idletras = idletras;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idventa")
    public Credito getCredito() {
        return this.credito;
    }

    public void setCredito(Credito credito) {
        this.credito = credito;
    }

    @Column(name = "montoletra", precision = 17, scale = 2)
    public BigDecimal getMontoletra() {
        return this.montoletra;
    }

    public void setMontoletra(BigDecimal montoletra) {
        this.montoletra = montoletra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecini", length = 23)
    public Date getFecini() {
        return this.fecini;
    }

    public void setFecini(Date fecini) {
        this.fecini = fecini;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecven", length = 23)
    public Date getFecven() {
        return this.fecven;
    }

    public void setFecven(Date fecven) {
        this.fecven = fecven;
    }

    @Column(name = "monto", precision = 17, scale = 2)
    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @Column(name = "interes", precision = 17, scale = 2)
    public BigDecimal getInteres() {
        return this.interes;
    }

    public void setInteres(BigDecimal interes) {
        this.interes = interes;
    }
    
    @Column(name = "saldo", precision = 17, scale = 2)
    public BigDecimal getSaldo() {
        return this.saldo;
    }

    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecreg", length = 23)
    public Date getFecreg() {
        return this.fecreg;
    }

    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }

    @Column(name = "estado", length = 2)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "descripcion", length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name = "mora", precision = 17, scale = 2)
    public BigDecimal getMora() {
        return this.mora;
    }

    public void setMora(BigDecimal mora) {
        this.mora = mora;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "letras")
    public Set getPagoses() {
        return this.pagoses;
    }

    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }

    @Column(name = "diffdays")
    public long getDiffdays() {
        return this.diffdays;
    }

    public void setDiffdays(long diffdays) {
        this.diffdays = diffdays;
    }
    
    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idletras != null)
                ? idletras.equals(((Letras) other).idletras)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idletras != null)
                ? (getClass().hashCode() + idletras.hashCode())
                : super.hashCode();
    }
}
