package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "menu", schema = "dbo", catalog = "cobranzas"
)
public class Menu implements java.io.Serializable {

    private Integer idmenu;
    private String menu;
    private String icon;
    private Date created;
    private Set submenus = new HashSet(0);
    private Set perfilmenus = new HashSet(0);

    public Menu() {
    }

    public Menu(Integer idmenu) {
        this.idmenu = idmenu;
    }

    public Menu(Integer idmenu, String menu, String icon, Date created, Set submenus, Set perfilmenus) {
        this.idmenu = idmenu;
        this.menu = menu;
        this.icon = icon;
        this.created = created;
        this.submenus = submenus;
        this.perfilmenus = perfilmenus;
    }

    @Id

    @Column(name = "idmenu", unique = true, nullable = false)
    public Integer getIdmenu() {
        return this.idmenu;
    }

    public void setIdmenu(Integer idmenu) {
        this.idmenu = idmenu;
    }

    @Column(name = "menu", length = 50)
    public String getMenu() {
        return this.menu;
    }

    public void setMenu(String menu) {
        this.menu = menu;
    }

    @Column(name = "icon", nullable = false, length = 50)
    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 23)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
    public Set getSubmenus() {
        return this.submenus;
    }

    public void setSubmenus(Set submenus) {
        this.submenus = submenus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
    public Set getPerfilmenus() {
        return this.perfilmenus;
    }

    public void setPerfilmenus(Set perfilmenus) {
        this.perfilmenus = perfilmenus;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idmenu != null)
                ? idmenu.equals(((Menu) other).idmenu)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idmenu != null)
                ? (getClass().hashCode() + idmenu.hashCode())
                : super.hashCode();
    }

}
