package Model;
// Generated 24/07/2015 09:15:20 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private int idmenu;
     private String nombre;
     private Date fechareg;
     private String imagen;
     private String url;
     private String action;
     private Integer raiz;
     private Integer orden;
     private Set<MenuTipoanexo> menuTipoanexos = new HashSet<MenuTipoanexo>(0);

    public Menu() {
    }

	
    public Menu(int idmenu) {
        this.idmenu = idmenu;
    }
    public Menu(int idmenu, String nombre, Date fechareg, String imagen, String url, String action, Integer raiz, Integer orden, Set<MenuTipoanexo> menuTipoanexos) {
       this.idmenu = idmenu;
       this.nombre = nombre;
       this.fechareg = fechareg;
       this.imagen = imagen;
       this.url = url;
       this.action = action;
       this.raiz = raiz;
       this.orden = orden;
       this.menuTipoanexos = menuTipoanexos;
    }
   
    public int getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(int idmenu) {
        this.idmenu = idmenu;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public Integer getRaiz() {
        return this.raiz;
    }
    
    public void setRaiz(Integer raiz) {
        this.raiz = raiz;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Set<MenuTipoanexo> getMenuTipoanexos() {
        return this.menuTipoanexos;
    }
    
    public void setMenuTipoanexos(Set<MenuTipoanexo> menuTipoanexos) {
        this.menuTipoanexos = menuTipoanexos;
    }




}


