package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Morosidad generated by hbm2java
 */
@Entity
@Table(name="morosidad"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Morosidad  implements java.io.Serializable {


     private int idmorosidad;
     private Date fecreg;
     private BigDecimal total;
     private BigDecimal vencida;
     private BigDecimal mora;
     private String tienda;

    public Morosidad() {
    }

	
    public Morosidad(int idmorosidad) {
        this.idmorosidad = idmorosidad;
    }
    public Morosidad(int idmorosidad, Date fecreg, BigDecimal total, BigDecimal vencida, BigDecimal mora, String tienda) {
       this.idmorosidad = idmorosidad;
       this.fecreg = fecreg;
       this.total = total;
       this.vencida = vencida;
       this.mora = mora;
       this.tienda = tienda;
    }
   
     @Id 

    
    @Column(name="idmorosidad", unique=true, nullable=false)
    public int getIdmorosidad() {
        return this.idmorosidad;
    }
    
    public void setIdmorosidad(int idmorosidad) {
        this.idmorosidad = idmorosidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecreg", length=23)
    public Date getFecreg() {
        return this.fecreg;
    }
    
    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }

    
    @Column(name="total", precision=17)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="vencida", precision=17)
    public BigDecimal getVencida() {
        return this.vencida;
    }
    
    public void setVencida(BigDecimal vencida) {
        this.vencida = vencida;
    }

    
    @Column(name="mora", precision=17)
    public BigDecimal getMora() {
        return this.mora;
    }
    
    public void setMora(BigDecimal mora) {
        this.mora = mora;
    }

    
    @Column(name="tienda", length=5)
    public String getTienda() {
        return this.tienda;
    }
    
    public void setTienda(String tienda) {
        this.tienda = tienda;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + this.idmorosidad;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Morosidad other = (Morosidad) obj;
        if (this.idmorosidad != other.idmorosidad) {
            return false;
        }
        return true;
    }




}


