package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "tipodoc", schema = "dbo", catalog = "cobranzas"
)
public class Movcaja implements java.io.Serializable {

    private Integer idmovcaja;    
    private BigDecimal monto;
    private String tipomov;
    private Caja caja; 
    private Date fechamov;

    public Movcaja() {
    }

    public Movcaja(Integer idmovcaja) {
        this.idmovcaja = idmovcaja;
    }

    public Movcaja(Integer idmovcaja, BigDecimal total, String tipomov, Caja caja) {
        this.idmovcaja = idmovcaja;        
        this.monto = total;
        this.tipomov = tipomov;
        this.caja = caja;                
    }

    @Id

    @Column(name = "idmovcaja", unique = true, nullable = false)
    public Integer getIdmovcaja() {
        return this.idmovcaja;
    }

    public void setIdmovcaja(Integer idmovcaja) {
        this.idmovcaja = idmovcaja;
    }
    
    @Column(name = "total", nullable = false, precision = 17)
    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    
    @Column(name = "tipomov", length = 2)
    public String getTipomov() {
        return this.tipomov;
    }

    public void setTipomov(String tipomov) {
        this.tipomov = tipomov;
    }  
           
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idcaja", nullable = false)
    public Caja getCaja() {
        return this.caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechamov", nullable = false, length = 23)
    public Date getFechamov() {
        return this.fechamov;
    }

    public void setFechamov(Date fechamov) {
        this.fechamov = fechamov;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idmovcaja != null)
                ? idmovcaja.equals(((Movcaja) other).idmovcaja)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idmovcaja != null)
                ? (getClass().hashCode() + idmovcaja.hashCode())
                : super.hashCode();
    }

}

