package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name="movimiento"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Movimiento  implements java.io.Serializable {


     private int id;
     private Integer cantidad;
     private String tipoingreso;
     private BigDecimal preciocompra;
     private BigDecimal precioventa;
     private Integer idrepuesto;

    public Movimiento() {
    }

	
    public Movimiento(int id) {
        this.id = id;
    }
    public Movimiento(int id, Integer cantidad, String tipoingreso, BigDecimal preciocompra, BigDecimal precioventa, Integer idrepuesto) {
       this.id = id;
       this.cantidad = cantidad;
       this.tipoingreso = tipoingreso;
       this.preciocompra = preciocompra;
       this.precioventa = precioventa;
       this.idrepuesto = idrepuesto;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="tipoingreso", length=10)
    public String getTipoingreso() {
        return this.tipoingreso;
    }
    
    public void setTipoingreso(String tipoingreso) {
        this.tipoingreso = tipoingreso;
    }

    
    @Column(name="preciocompra", precision=18)
    public BigDecimal getPreciocompra() {
        return this.preciocompra;
    }
    
    public void setPreciocompra(BigDecimal preciocompra) {
        this.preciocompra = preciocompra;
    }

    
    @Column(name="precioventa", precision=18)
    public BigDecimal getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(BigDecimal precioventa) {
        this.precioventa = precioventa;
    }

    
    @Column(name="idrepuesto")
    public Integer getIdrepuesto() {
        return this.idrepuesto;
    }
    
    public void setIdrepuesto(Integer idrepuesto) {
        this.idrepuesto = idrepuesto;
    }




}


