package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Numeracion generated by hbm2java
 */
@Entity
@Table(name="numeracion"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Numeracion  implements java.io.Serializable {


     private int idnumeracion;
     private Tipodoc tipodoc;
     private String serie;
     private Integer correlativo;

    public Numeracion() {
    }

	
    public Numeracion(int idnumeracion) {
        this.idnumeracion = idnumeracion;
    }
    public Numeracion(int idnumeracion, Tipodoc tipodoc, String serie, Integer correlativo) {
       this.idnumeracion = idnumeracion;
       this.tipodoc = tipodoc;
       this.serie = serie;
       this.correlativo = correlativo;
    }
   
     @Id 

    
    @Column(name="idnumeracion", unique=true, nullable=false)
    public int getIdnumeracion() {
        return this.idnumeracion;
    }
    
    public void setIdnumeracion(int idnumeracion) {
        this.idnumeracion = idnumeracion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipodoc")
    public Tipodoc getTipodoc() {
        return this.tipodoc;
    }
    
    public void setTipodoc(Tipodoc tipodoc) {
        this.tipodoc = tipodoc;
    }

    
    @Column(name="serie", length=50)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }

    
    @Column(name="correlativo")
    public Integer getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(Integer correlativo) {
        this.correlativo = correlativo;
    }




}


