package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ocupacion generated by hbm2java
 */
@Entity
@Table(name = "ocupacion", schema = "dbo", catalog = "cobranzas"
)
public class Ocupacion implements java.io.Serializable {

    private Integer idocupacion;
    private Anexo anexo;
    private String tipo;
    private String clase;
    private String descripcion;
    private String empresa;
    private BigDecimal montoin;
    private Boolean boletas;
    private Boolean rrhh;
    private Boolean facbol;
    private Boolean constancia;
    private Boolean tpropiedad;
    private Boolean licencia;
    private Boolean pagosunat;
    private Boolean func;    

    public Ocupacion() {
    }

    public Ocupacion(Integer idocupacion, Anexo anexo) {
        this.idocupacion = idocupacion;
        this.anexo = anexo;
    }

    public Ocupacion(Integer idocupacion, Anexo anexo, String tipo, String clase, String descripcion, String empresa, BigDecimal montoin, Boolean boletas, Boolean rrhh, Boolean facbol, Boolean constancia, Boolean tpropiedad, Boolean licencia, Boolean pagosunat, Boolean func) {
        this.idocupacion = idocupacion;
        this.anexo = anexo;
        this.tipo = tipo;
        this.clase = clase;
        this.descripcion = descripcion;
        this.empresa = empresa;
        this.montoin = montoin;
        this.boletas = boletas;
        this.rrhh = rrhh;
        this.facbol = facbol;
        this.constancia = constancia;
        this.tpropiedad = tpropiedad;
        this.licencia = licencia;
        this.pagosunat = pagosunat;
        this.func = func;        
    }

    @Id

    @Column(name = "idocupacion", unique = true, nullable = false)
    public Integer getIdocupacion() {
        return this.idocupacion;
    }

    public void setIdocupacion(Integer idocupacion) {
        this.idocupacion = idocupacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idanexo", nullable = false)
    public Anexo getAnexo() {
        return this.anexo;
    }

    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

    @Column(name = "tipo", length = 2)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Column(name = "clase", length = 2)
    public String getClase() {
        return this.clase;
    }

    public void setClase(String clase) {
        this.clase = clase;
    }

    @Column(name = "descripcion", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "empresa", length = 50)
    public String getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    @Column(name = "montoin", precision = 17)
    public BigDecimal getMontoin() {
        return this.montoin;
    }

    public void setMontoin(BigDecimal montoin) {
        this.montoin = montoin;
    }

    @Column(name = "boletas")
    public Boolean getBoletas() {
        return this.boletas;
    }

    public void setBoletas(Boolean boletas) {
        this.boletas = boletas;
    }

    @Column(name = "rrhh")
    public Boolean getRrhh() {
        return this.rrhh;
    }

    public void setRrhh(Boolean rrhh) {
        this.rrhh = rrhh;
    }

    @Column(name = "facbol")
    public Boolean getFacbol() {
        return this.facbol;
    }

    public void setFacbol(Boolean facbol) {
        this.facbol = facbol;
    }

    @Column(name = "constancia")
    public Boolean getConstancia() {
        return this.constancia;
    }

    public void setConstancia(Boolean constancia) {
        this.constancia = constancia;
    }

    @Column(name = "tpropiedad")
    public Boolean getTpropiedad() {
        return this.tpropiedad;
    }

    public void setTpropiedad(Boolean tpropiedad) {
        this.tpropiedad = tpropiedad;
    }

    @Column(name = "licencia")
    public Boolean getLicencia() {
        return this.licencia;
    }

    public void setLicencia(Boolean licencia) {
        this.licencia = licencia;
    }

    @Column(name = "pagosunat")
    public Boolean getPagosunat() {
        return this.pagosunat;
    }

    public void setPagosunat(Boolean pagosunat) {
        this.pagosunat = pagosunat;
    }
    
    @Column(name = "func")
    public Boolean getFunc() {
        return this.func;
    }

    public void setFunc(Boolean func) {
        this.func = func;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idocupacion != null)
                ? idocupacion.equals(((Ocupacion) other).idocupacion)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idocupacion != null)
                ? (getClass().hashCode() + idocupacion.hashCode())
                : super.hashCode();
    }

}
