package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Operaciondetalle generated by hbm2java
 */
@Entity
@Table(name = "operaciondetalle",
         schema = "dbo",
         catalog = "cobranzas"
)
public class Operaciondetalle implements java.io.Serializable {

    private Integer idoperaciondetalle;
    private Articulo articulo;
    private Operacion operacion;
    private String codigoproducto;
    private String descripcion;
    private Integer cantidadanterior;
    private Integer cantidad;
    private BigDecimal preciocompraanterior;
    private BigDecimal preciocompra;
    private BigDecimal precioventaanterior;
    private BigDecimal precioventa;
    private BigDecimal costopromedioanterior;
    private BigDecimal costopromedio;
    private BigDecimal preciototal;

    public Operaciondetalle() {
    }

    public Operaciondetalle(Integer idoperaciondetalle) {
        this.idoperaciondetalle = idoperaciondetalle;
    }

    public Operaciondetalle(Integer idoperaciondetalle, Articulo articulo, Operacion operacion, String codigoproducto, String descripcion, Integer cantidadanterior, Integer cantidad, BigDecimal preciocompraanterior, BigDecimal preciocompra, BigDecimal precioventaanterior, BigDecimal precioventa, BigDecimal costopromedioanterior, BigDecimal costopromedio, BigDecimal preciototal) {
        this.idoperaciondetalle = idoperaciondetalle;
        this.articulo = articulo;
        this.operacion = operacion;
        this.codigoproducto = codigoproducto;
        this.descripcion = descripcion;
        this.cantidadanterior = cantidadanterior;
        this.cantidad = cantidad;
        this.preciocompraanterior = preciocompraanterior;
        this.preciocompra = preciocompra;
        this.precioventaanterior = precioventaanterior;
        this.precioventa = precioventa;
        this.costopromedioanterior = costopromedioanterior;
        this.costopromedio = costopromedio;
        this.preciototal = preciototal;
    }

    @Id

    @Column(name = "idoperaciondetalle", unique = true, nullable = false)
    public Integer getIdoperaciondetalle() {
        return this.idoperaciondetalle;
    }

    public void setIdoperaciondetalle(Integer idoperaciondetalle) {
        this.idoperaciondetalle = idoperaciondetalle;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idarticulo")
    public Articulo getArticulo() {
        return this.articulo;
    }

    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idoperacion")
    public Operacion getOperacion() {
        return this.operacion;
    }

    public void setOperacion(Operacion operacion) {
        this.operacion = operacion;
    }

    @Column(name = "codigoproducto", length = 10)
    public String getCodigoproducto() {
        return this.codigoproducto;
    }

    public void setCodigoproducto(String codigoproducto) {
        this.codigoproducto = codigoproducto;
    }

    @Column(name = "descripcion", length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "cantidadanterior")
    public Integer getCantidadanterior() {
        return this.cantidadanterior;
    }

    public void setCantidadanterior(Integer cantidadanterior) {
        this.cantidadanterior = cantidadanterior;
    }

    @Column(name = "cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "preciocompraanterior", precision = 18)
    public BigDecimal getPreciocompraanterior() {
        return this.preciocompraanterior;
    }

    public void setPreciocompraanterior(BigDecimal preciocompraanterior) {
        this.preciocompraanterior = preciocompraanterior;
    }

    @Column(name = "preciocompra", precision = 18)
    public BigDecimal getPreciocompra() {
        return this.preciocompra;
    }

    public void setPreciocompra(BigDecimal preciocompra) {
        this.preciocompra = preciocompra;
    }

    @Column(name = "precioventaanterior", precision = 18)
    public BigDecimal getPrecioventaanterior() {
        return this.precioventaanterior;
    }

    public void setPrecioventaanterior(BigDecimal precioventaanterior) {
        this.precioventaanterior = precioventaanterior;
    }

    @Column(name = "precioventa", precision = 18)
    public BigDecimal getPrecioventa() {
        return this.precioventa;
    }

    public void setPrecioventa(BigDecimal precioventa) {
        this.precioventa = precioventa;
    }

    @Column(name = "costopromedioanterior", precision = 18)
    public BigDecimal getCostopromedioanterior() {
        return this.costopromedioanterior;
    }

    public void setCostopromedioanterior(BigDecimal costopromedioanterior) {
        this.costopromedioanterior = costopromedioanterior;
    }

    @Column(name = "costopromedio", precision = 18)
    public BigDecimal getCostopromedio() {
        return this.costopromedio;
    }

    public void setCostopromedio(BigDecimal costopromedio) {
        this.costopromedio = costopromedio;
    }

    @Column(name = "preciototal", precision = 18)
    public BigDecimal getPreciototal() {
        return this.preciototal;
    }

    public void setPreciototal(BigDecimal preciototal) {
        this.preciototal = preciototal;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idoperaciondetalle != null)
                ? idoperaciondetalle.equals(((Operaciondetalle) other).idoperaciondetalle)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idoperaciondetalle != null)
                ? (getClass().hashCode() + idoperaciondetalle.hashCode())
                : super.hashCode();
    }
}
