package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "operaciondetalle", schema = "dbo", catalog = "cobranzas"
)
public class Operaciondetalle implements java.io.Serializable {

    private Integer idoperaciondetalle;
    private Operacion operacion;
    private Articulo articulo;
    private String codigoproducto;
    private String descripcion;
    private Integer cantidadanterior;
    private Integer cantidad;
    private BigDecimal precio;
    private BigDecimal preciototal;
    private BigDecimal costopromedio;

    public Operaciondetalle() {
    }

    public Operaciondetalle(Integer idoperaciondetalle) {
        this.idoperaciondetalle = idoperaciondetalle;
    }

    public Operaciondetalle(Integer idoperaciondetalle, Operacion operacion, Articulo articulo, String codigoproducto, String descripcion, Integer cantidadanterior, Integer cantidad, BigDecimal precio, BigDecimal preciototal, BigDecimal costopromedio) {
        this.idoperaciondetalle = idoperaciondetalle;
        this.operacion = operacion;
        this.articulo = articulo;
        this.codigoproducto = codigoproducto;
        this.descripcion = descripcion;
        this.cantidadanterior = cantidadanterior;
        this.cantidad = cantidad;
        this.precio = precio;
        this.preciototal = preciototal;
        this.costopromedio = costopromedio;
    }

    @Id

    @Column(name = "idoperaciondetalle", unique = true, nullable = false)
    public Integer getIdoperaciondetalle() {
        return this.idoperaciondetalle;
    }

    public void setIdoperaciondetalle(Integer idoperaciondetalle) {
        this.idoperaciondetalle = idoperaciondetalle;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idoperacion", nullable = false)
    public Operacion getOperacion() {
        return this.operacion;
    }

    public void setOperacion(Operacion operacion) {
        this.operacion = operacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idarticulo", nullable = false)
    public Articulo getArticulo() {
        return this.articulo;
    }

    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }

    @Column(name = "codigoproducto", nullable = false, length = 10)
    public String getCodigoproducto() {
        return this.codigoproducto;
    }

    public void setCodigoproducto(String codigoproducto) {
        this.codigoproducto = codigoproducto;
    }

    @Column(name = "descripcion", nullable = false, length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "cantidadanterior")
    public Integer getCantidadanterior() {
        return this.cantidadanterior;
    }

    public void setCantidadanterior(Integer cantidadanterior) {
        this.cantidadanterior = cantidadanterior;
    }

    @Column(name = "cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "precio", nullable = false, precision = 18)
    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    @Column(name = "preciototal", nullable = false, precision = 18)
    public BigDecimal getPreciototal() {
        return this.preciototal;
    }

    public void setPreciototal(BigDecimal preciototal) {
        this.preciototal = preciototal;
    }

    @Column(name = "costopromedio", nullable = false, precision = 18)
    public BigDecimal getCostopromedio() {
        return this.costopromedio;
    }

    public void setCostopromedio(BigDecimal costopromedio) {
        this.costopromedio = costopromedio;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idoperaciondetalle != null)
                ? idoperaciondetalle.equals(((Operaciondetalle) other).idoperaciondetalle)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idoperaciondetalle != null)
                ? (getClass().hashCode() + idoperaciondetalle.hashCode())
                : super.hashCode();
    }

}
