package Model;
// Generated 30/07/2015 11:43:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name="pago"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Pago  implements java.io.Serializable {


     private int idpago;
     private Condicionpago condicionpago;
     private BigDecimal monto;
     private Date fechareg;
     private String descuento;
     private String igv;
     private Set ventas = new HashSet(0);

    public Pago() {
    }

	
    public Pago(int idpago, Condicionpago condicionpago) {
        this.idpago = idpago;
        this.condicionpago = condicionpago;
    }
    public Pago(int idpago, Condicionpago condicionpago, BigDecimal monto, Date fechareg, String descuento, String igv, Set ventas) {
       this.idpago = idpago;
       this.condicionpago = condicionpago;
       this.monto = monto;
       this.fechareg = fechareg;
       this.descuento = descuento;
       this.igv = igv;
       this.ventas = ventas;
    }
   
     @Id 

    
    @Column(name="idpago", unique=true, nullable=false)
    public int getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(int idpago) {
        this.idpago = idpago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcondicionpago", nullable=false)
    public Condicionpago getCondicionpago() {
        return this.condicionpago;
    }
    
    public void setCondicionpago(Condicionpago condicionpago) {
        this.condicionpago = condicionpago;
    }

    
    @Column(name="monto", precision=17, scale=4)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechareg", length=23)
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

    
    @Column(name="descuento", length=18)
    public String getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(String descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="igv", length=18)
    public String getIgv() {
        return this.igv;
    }
    
    public void setIgv(String igv) {
        this.igv = igv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pago")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


