package Model;
// Generated 24/07/2015 09:15:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idpago;
     private CondicionPago condicionPago;
     private BigDecimal monto;
     private Date fechareg;
     private String descuento;
     private String igv;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Pago() {
    }

	
    public Pago(int idpago, CondicionPago condicionPago) {
        this.idpago = idpago;
        this.condicionPago = condicionPago;
    }
    public Pago(int idpago, CondicionPago condicionPago, BigDecimal monto, Date fechareg, String descuento, String igv, Set<Venta> ventas) {
       this.idpago = idpago;
       this.condicionPago = condicionPago;
       this.monto = monto;
       this.fechareg = fechareg;
       this.descuento = descuento;
       this.igv = igv;
       this.ventas = ventas;
    }
   
    public int getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(int idpago) {
        this.idpago = idpago;
    }
    public CondicionPago getCondicionPago() {
        return this.condicionPago;
    }
    
    public void setCondicionPago(CondicionPago condicionPago) {
        this.condicionPago = condicionPago;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }
    public String getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(String descuento) {
        this.descuento = descuento;
    }
    public String getIgv() {
        return this.igv;
    }
    
    public void setIgv(String igv) {
        this.igv = igv;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


