package Model;
// Generated 03/09/2015 12:09:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "pagos", schema = "dbo", catalog = "cobranzas"
)
public class Pagos implements java.io.Serializable {

    private Integer idpagos;
    private Letras letras;
    private String operacion;
    private BigDecimal monto;
    private Date fecreg;
    private String descripcion;
    private String tipo;
    private Integer usuario;

    public Pagos() {
    }

    public Pagos(Integer idpagos) {
        this.idpagos = idpagos;
    }

    public Pagos(Integer idpagos, Letras letras, String operacion, BigDecimal monto, Date fecreg, String descripcion, String tipo, Integer usuario) {
        this.idpagos = idpagos;
        this.letras = letras;
        this.operacion = operacion;
        this.monto = monto;
        this.fecreg = fecreg;
        this.descripcion = descripcion;
        this.tipo=tipo;
        this.usuario=usuario;
    }

    @Id

    @Column(name = "idpagos", unique = true, nullable = false)
    public Integer getIdpagos() {
        return this.idpagos;
    }

    public void setIdpagos(Integer idpagos) {
        this.idpagos = idpagos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idletras")
    public Letras getLetras() {
        return this.letras;
    }

    public void setLetras(Letras letras) {
        this.letras = letras;
    }

    @Column(name = "operacion", length = 20)
    public String getOperacion() {
        return this.operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    @Column(name = "monto", precision = 17, scale = 2)
    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecreg", length = 23)
    public Date getFecreg() {
        return this.fecreg;
    }

    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }

    @Column(name = "descripcion", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name = "tipo", length = 2)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }


    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idpagos != null)
                ? idpagos.equals(((Pagos) other).idpagos)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idpagos != null)
                ? (getClass().hashCode() + idpagos.hashCode())
                : super.hashCode();
    }

}
