package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfilmenu generated by hbm2java
 */
@Entity
@Table(name = "perfilmenu",
         schema = "dbo",
         catalog = "cobranzas"
)
public class Perfilmenu implements java.io.Serializable {

    private Integer idperfilmenu;
    private Menu menu;
    private Perfil perfil;
    private Boolean estado;
    private Set perfilsubmenus = new HashSet(0);

    public Perfilmenu() {
    }

    public Perfilmenu(Integer idperfilmenu) {
        this.idperfilmenu = idperfilmenu;
    }

    public Perfilmenu(Integer idperfilmenu, Menu menu, Perfil perfil, Boolean estado, Set perfilsubmenus) {
        this.idperfilmenu = idperfilmenu;
        this.menu = menu;
        this.perfil = perfil;
        this.estado = estado;
        this.perfilsubmenus = perfilsubmenus;
    }

    @Id

    @Column(name = "idperfilmenu", unique = true, nullable = false)
    public Integer getIdperfilmenu() {
        return this.idperfilmenu;
    }

    public void setIdperfilmenu(Integer idperfilmenu) {
        this.idperfilmenu = idperfilmenu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idmenu")
    public Menu getMenu() {
        return this.menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idperfil")
    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    @Column(name = "estado")
    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfilmenu")
    public Set getPerfilsubmenus() {
        return this.perfilsubmenus;
    }

    public void setPerfilsubmenus(Set perfilsubmenus) {
        this.perfilsubmenus = perfilsubmenus;
    }

    @Override
    public int hashCode() {
        return (idperfilmenu != null)
                ? (getClass().hashCode() + idperfilmenu.hashCode())
                : super.hashCode();
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idperfilmenu != null)
                ? idperfilmenu.equals(((Perfilmenu) other).idperfilmenu)
                : (other == this);
    }

}
