package Model;
// Generated 21/08/2015 05:10:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="perfil"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Perfil  implements java.io.Serializable {


     private Integer idperfil;
     private String descripcion;
     private Boolean mananexo;
     private Boolean mancolor;
     private Boolean mancondicion;
     private Boolean manmodelo;
     private Boolean mantanexo;
     private Boolean mantpago;
     private Boolean mantvehiculo;
     private Boolean manusuario;
     private Boolean manvehiculo;
     private Boolean manventa;
     private Boolean mandatoscre;
     private Boolean manpago;
     private Boolean manletras;
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(Integer idperfil) {
        this.idperfil = idperfil;
    }
    public Perfil(Integer idperfil, String descripcion, Boolean mananexo, Boolean mancolor, Boolean mancondicion, Boolean manmodelo, Boolean mantanexo, Boolean mantpago, Boolean mantvehiculo, Boolean manusuario, Boolean manvehiculo, Boolean manventa, Boolean mandatoscre, Boolean manpago, Boolean manletras, Set usuarios) {
       this.idperfil = idperfil;
       this.descripcion = descripcion;
       this.mananexo = mananexo;
       this.mancolor = mancolor;
       this.mancondicion = mancondicion;
       this.manmodelo = manmodelo;
       this.mantanexo = mantanexo;
       this.mantpago = mantpago;
       this.mantvehiculo = mantvehiculo;
       this.manusuario = manusuario;
       this.manvehiculo = manvehiculo;
       this.manventa = manventa;
       this.mandatoscre = mandatoscre;
       this.manpago = manpago;
       this.manletras = manletras;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="idperfil", unique=true, nullable=false)
    public Integer getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(Integer idperfil) {
        this.idperfil = idperfil;
    }

    
    @Column(name="descripcion", length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="mananexo")
    public Boolean getMananexo() {
        return this.mananexo;
    }
    
    public void setMananexo(Boolean mananexo) {
        this.mananexo = mananexo;
    }

    
    @Column(name="mancolor")
    public Boolean getMancolor() {
        return this.mancolor;
    }
    
    public void setMancolor(Boolean mancolor) {
        this.mancolor = mancolor;
    }

    
    @Column(name="mancondicion")
    public Boolean getMancondicion() {
        return this.mancondicion;
    }
    
    public void setMancondicion(Boolean mancondicion) {
        this.mancondicion = mancondicion;
    }

    
    @Column(name="manmodelo")
    public Boolean getManmodelo() {
        return this.manmodelo;
    }
    
    public void setManmodelo(Boolean manmodelo) {
        this.manmodelo = manmodelo;
    }

    
    @Column(name="mantanexo")
    public Boolean getMantanexo() {
        return this.mantanexo;
    }
    
    public void setMantanexo(Boolean mantanexo) {
        this.mantanexo = mantanexo;
    }

    
    @Column(name="mantpago")
    public Boolean getMantpago() {
        return this.mantpago;
    }
    
    public void setMantpago(Boolean mantpago) {
        this.mantpago = mantpago;
    }

    
    @Column(name="mantvehiculo")
    public Boolean getMantvehiculo() {
        return this.mantvehiculo;
    }
    
    public void setMantvehiculo(Boolean mantvehiculo) {
        this.mantvehiculo = mantvehiculo;
    }

    
    @Column(name="manusuario")
    public Boolean getManusuario() {
        return this.manusuario;
    }
    
    public void setManusuario(Boolean manusuario) {
        this.manusuario = manusuario;
    }

    
    @Column(name="manvehiculo")
    public Boolean getManvehiculo() {
        return this.manvehiculo;
    }
    
    public void setManvehiculo(Boolean manvehiculo) {
        this.manvehiculo = manvehiculo;
    }

    
    @Column(name="manventa")
    public Boolean getManventa() {
        return this.manventa;
    }
    
    public void setManventa(Boolean manventa) {
        this.manventa = manventa;
    }

    
    @Column(name="mandatoscre")
    public Boolean getMandatoscre() {
        return this.mandatoscre;
    }
    
    public void setMandatoscre(Boolean mandatoscre) {
        this.mandatoscre = mandatoscre;
    }

    
    @Column(name="manpago")
    public Boolean getManpago() {
        return this.manpago;
    }
    
    public void setManpago(Boolean manpago) {
        this.manpago = manpago;
    }

    
    @Column(name="manletras")
    public Boolean getManletras() {
        return this.manletras;
    }
    
    public void setManletras(Boolean manletras) {
        this.manletras = manletras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perfil")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idperfil != null)
            ? idperfil.equals(((Perfil) other).idperfil)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (idperfil != null) 
            ? (getClass().hashCode() + idperfil.hashCode())
            : super.hashCode();
    }


}


