package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "perfilsubmenu", schema = "dbo", catalog = "cobranzas"
)
public class Perfilsubmenu implements java.io.Serializable {

    private Integer idperfilsubmenu;
    private Perfilmenu perfilmenu;
    private Submenu submenu;
    private Boolean estado;

    public Perfilsubmenu() {
    }

    public Perfilsubmenu(Integer idperfilsubmenu) {
        this.idperfilsubmenu = idperfilsubmenu;
    }

    public Perfilsubmenu(Integer idperfilsubmenu, Perfilmenu perfilmenu, Submenu submenu, Boolean estado) {
        this.idperfilsubmenu = idperfilsubmenu;
        this.perfilmenu = perfilmenu;
        this.submenu = submenu;
        this.estado = estado;
    }

    @Id
    @Column(name = "idperfilsubmenu", unique = true, nullable = false)
    public Integer getIdperfilsubmenu() {
        return this.idperfilsubmenu;
    }

    public void setIdperfilsubmenu(Integer idperfilsubmenu) {
        this.idperfilsubmenu = idperfilsubmenu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idperfilmenu")
    public Perfilmenu getPerfilmenu() {
        return this.perfilmenu;
    }

    public void setPerfilmenu(Perfilmenu perfilmenu) {
        this.perfilmenu = perfilmenu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idsubmenu")
    public Submenu getSubmenu() {
        return this.submenu;
    }

    public void setSubmenu(Submenu submenu) {
        this.submenu = submenu;
    }

    @Column(name = "estado")
    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idperfilsubmenu != null)
                ? idperfilsubmenu.equals(((Perfilsubmenu) other).idperfilsubmenu)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idperfilsubmenu != null)
                ? (getClass().hashCode() + idperfilsubmenu.hashCode())
                : super.hashCode();
    }

}
