package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "perfilmenu", schema = "dbo", catalog = "cobranzas"
)
public class Perfilmenu implements java.io.Serializable {

    private Integer idperfilmenu;
    private Perfil perfil;
    private Menu menu;
    private Boolean estado;

    public Perfilmenu() {
    }

    public Perfilmenu(Integer idperfilmenu) {
        this.idperfilmenu = idperfilmenu;
    }

    public Perfilmenu(Integer idperfilmenu, Perfil perfil, Menu menu, Boolean estado) {
        this.idperfilmenu = idperfilmenu;
        this.perfil = perfil;
        this.menu = menu;
        this.estado = estado;
    }

    @Id
    @Column(name = "idperfilmenu", unique = true, nullable = false)
    public Integer getIdperfilmenu() {
        return this.idperfilmenu;
    }

    public void setIdperfilmenu(Integer idperfilmenu) {
        this.idperfilmenu = idperfilmenu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idperfil")
    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idmenu")
    public Menu getMenu() {
        return this.menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    @Column(name = "estado")
    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idperfilmenu != null)
                ? idperfilmenu.equals(((Perfilmenu) other).idperfilmenu)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idperfilmenu != null)
                ? (getClass().hashCode() + idperfilmenu.hashCode())
                : super.hashCode();
    }

}
