package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "dbo", catalog = "cobranzas"
)
public class Perfil implements java.io.Serializable {

    private Integer idperfil;
    private String descripcion;
    private String abrev;
    private Set usuarios = new HashSet(0);
    private Set perfilmenus = new HashSet(0);

    public Perfil() {
    }

    public Perfil(Integer idperfil) {
        this.idperfil = idperfil;
    }

    public Perfil(Integer idperfil, String descripcion, String abrev, Set usuarios, Set perfilmenus) {
        this.idperfil = idperfil;
        this.descripcion = descripcion;
        this.abrev = abrev;
        this.usuarios = usuarios;
        this.perfilmenus = perfilmenus;
    }

    @Id

    @Column(name = "idperfil", unique = true, nullable = false)
    public Integer getIdperfil() {
        return this.idperfil;
    }

    public void setIdperfil(Integer idperfil) {
        this.idperfil = idperfil;
    }

    @Column(name = "descripcion", length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name = "abrev", length = 2)
    public String getAbrev() {
        return this.abrev;
    }

    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
    public Set getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
    public Set getPerfilmenus() {
        return this.perfilmenus;
    }

    public void setPerfilmenus(Set perfilmenus) {
        this.perfilmenus = perfilmenus;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idperfil != null)
                ? idperfil.equals(((Perfil) other).idperfil)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idperfil != null)
                ? (getClass().hashCode() + idperfil.hashCode())
                : super.hashCode();
    }

}
