package Model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Conceptos generated by master
 */
@Entity
@Table(name = "requisitos", schema = "dbo", catalog = "cobranzas"
)
public class Requisitos implements java.io.Serializable {

    private Integer idrequisitos;
    private Credito credito;
    private String copdni;
    private Boolean copiadni;
    private String recibagua;
    private Boolean reciboagua;
    private String recibluz;
    private Boolean reciboluz;
    private String croq;
    private Boolean croquis;
    private String copiadnicon;
    private Boolean copiadniconyuge;
    private String otrosobs;
    private Boolean otros;
    

    public Requisitos() {
    }

    public Requisitos(Integer idconceptos) {
        this.idrequisitos = idconceptos;
    }

    public Requisitos(Integer idconceptos, Credito credito, String copdni, Boolean copiadni, String recibagua, Boolean reciboagua, String recibluz, Boolean reciboluz, String croq, Boolean croquis, String copiadnicon, Boolean copiadniconyuge, String otrosobs, Boolean otros) {
        this.idrequisitos = idconceptos;
        this.credito = credito;
        this.copdni = copdni;
        this.copiadni = copiadni;
        this.recibagua = recibagua;
        this.reciboagua = reciboagua;
        this.recibluz = recibluz;
        this.reciboluz = reciboluz;
        this.croq = croq;
        this.croquis = croquis;
        this.copiadnicon = copiadnicon;
        this.copiadniconyuge = copiadniconyuge;
        this.otrosobs = otrosobs;
        this.otros = otros;
    }

    @Id

    @Column(name = "idconceptos", unique = true, nullable = false)
    public Integer getIdrequisitos() {
        return this.idrequisitos;
    }

    public void setIdrequisitos(Integer idconceptos) {
        this.idrequisitos = idconceptos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idventa")
    public Credito getCredito() {
        return this.credito;
    }

    public void setCredito(Credito credito) {
        this.credito = credito;
    }
    
    @Column(name = "copdni", length = 20)
    public String getCopdni() {
        return this.copdni;
    }    

    public void setCopdni(String copdni) {
        this.copdni = copdni;
    }
    
    @Column(name = "copiadni")
    public Boolean getCopiadni() {
        return this.copiadni;
    }

    public void setCopiadni(Boolean copiadni) {
        this.copiadni = copiadni;
    }
    
    @Column(name = "recibagua", length = 20)
    public String getRecibagua() {
        return this.recibagua;
    }    

    public void setRecibagua(String recibagua) {
        this.recibagua = recibagua;
    }
    
    @Column(name = "reciboagua")
    public Boolean getReciboagua() {
        return this.reciboagua;
    }

    public void setReciboagua(Boolean reciboagua) {
        this.reciboagua = reciboagua;
    }
    
    @Column(name = "recibluz", length = 20)
    public String getRecibluz() {
        return this.recibluz;
    }    

    public void setRecibluz(String recibluz) {
        this.recibluz = recibluz;
    }
    
    @Column(name = "reciboluz")
    public Boolean getReciboluz() {
        return this.reciboluz;
    }

    public void setReciboluz(Boolean reciboluz) {
        this.reciboluz = reciboluz;
    }    
    
    @Column(name = "croq", length = 20)
    public String getCroq() {
        return this.croq;
    }    

    public void setCroq(String croq) {
        this.croq = croq;
    }
    
    @Column(name = "croquis")
    public Boolean getCroquis() {
        return this.croquis;
    }

    public void setCroquis(Boolean croquis) {
        this.croquis = croquis;
    }
    
    @Column(name = "copiadnicon", length = 20)
    public String getCopiadnicon() {
        return this.copiadnicon;
    }    

    public void setCopiadnicon(String copiadnicon) {
        this.copiadnicon = copiadnicon;
    }
    
    @Column(name = "copiadniconyuge")
    public Boolean getCopiadniconyuge() {
        return this.copiadniconyuge;
    }

    public void setCopiadniconyuge(Boolean copiadniconyuge) {
        this.copiadniconyuge = copiadniconyuge;
    }
    
    @Column(name = "otrosobs", length = 20)
    public String getOtrosobs() {
        return this.otrosobs;
    }    

    public void setOtrosobs(String otrosobs) {
        this.otrosobs = otrosobs;
    }
    
    @Column(name = "otros")
    public Boolean getOtros() {
        return this.otros;
    }

    public void setOtros(Boolean otros) {
        this.otros = otros;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idrequisitos != null)
                ? idrequisitos.equals(((Requisitos) other).idrequisitos)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idrequisitos != null)
                ? (getClass().hashCode() + idrequisitos.hashCode())
                : super.hashCode();
    }

}
