package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "soporte",
        schema = "dbo",
        catalog = "cobranzas"
)
public class Soporte implements java.io.Serializable {

    private Integer idsoporte;
    private Tiposoporte tiposoporte;
    private Anexo anexo;
    private Vehiculo vehiculo;
    private Anexo vendedor;
    private Anexo usuario;
    private Character recibo;
    private String reporte;
    private String condicion;
    private String nota;
    private Integer estado;
    private Date ingreso;
    private Date salida;
    private Date created;

    public Soporte() {
    }

    public Soporte(Integer idsoporte, Tiposoporte tiposoporte, Anexo anexo, Vehiculo vehiculo, Anexo vendedor, Anexo usuario, Character recibo, String reporte, String condicion, String nota, Integer estado, Date ingreso, Date salida, Date created) {
        this.idsoporte = idsoporte;
        this.tiposoporte = tiposoporte;
        this.anexo = anexo;
        this.vehiculo = vehiculo;
        this.vendedor = vendedor;
        this.usuario = usuario;
        this.recibo = recibo;
        this.reporte = reporte;
        this.condicion = condicion;
        this.nota = nota;
        this.estado = estado;
        this.ingreso = ingreso;
        this.salida = salida;
        this.created = created;
    }

    @Id
    @Column(name = "idsoporte", unique = true, nullable = false)
    public Integer getIdsoporte() {
        return this.idsoporte;
    }

    public void setIdsoporte(Integer idsoporte) {
        this.idsoporte = idsoporte;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idtiposoporte", nullable = false)
    public Tiposoporte getTiposoporte() {
        return this.tiposoporte;
    }

    public void setTiposoporte(Tiposoporte tiposoporte) {
        this.tiposoporte = tiposoporte;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idanexo", nullable = false)
    public Anexo getAnexo() {
        return this.anexo;
    }

    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idvehiculo", nullable = false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }

    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idvendedor", nullable = false)
    public Anexo getVendedor() {
        return this.vendedor;
    }

    public void setVendedor(Anexo vendedor) {
        this.vendedor = vendedor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idusuario", nullable = false)
    public Anexo getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Anexo usuario) {
        this.usuario = usuario;
    }

    @Column(name = "recibo", length = 10)
    public Character getRecibo() {
        return this.recibo;
    }

    public void setRecibo(Character recibo) {
        this.recibo = recibo;
    }

    @Column(name = "reporte", nullable = false, length = 250)
    public String getReporte() {
        return this.reporte;
    }

    public void setReporte(String reporte) {
        this.reporte = reporte;
    }

    @Column(name = "condicion", length = 250)
    public String getCondicion() {
        return this.condicion;
    }

    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    @Column(name = "nota", length = 50)
    public String getNota() {
        return this.nota;
    }

    public void setNota(String nota) {
        this.nota = nota;
    }

    @Column(name = "estado", nullable = false)
    public Integer getEstado() {
        return this.estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ingreso", length = 23)
    public Date getIngreso() {
        return this.ingreso;
    }

    public void setIngreso(Date ingreso) {
        this.ingreso = ingreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "salida", length = 23)
    public Date getSalida() {
        return this.salida;
    }

    public void setSalida(Date salida) {
        this.salida = salida;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", length = 23)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idsoporte != null)
                ? idsoporte.equals(((Soporte) other).idsoporte)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idsoporte != null)
                ? (getClass().hashCode() + idsoporte.hashCode())
                : super.hashCode();
    }

}
