package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "subfamilia", schema = "dbo", catalog = "cobranzas"
)
public class Subfamilia implements java.io.Serializable {

    private Integer idsubfamilia;
    private String subfamilia;
    private Familia familia;
    private Date created;
    private String numero;

    public Subfamilia() {
    }

    public Subfamilia(Integer idsubfamilia) {
        this.idsubfamilia = idsubfamilia;
    }

    public Subfamilia(Integer idsubfamilia, String subfamilia, Familia familia, Date created, String numero) {
        this.idsubfamilia = idsubfamilia;
        this.subfamilia = subfamilia;
        this.familia = familia;
        this.created = created;
        this.numero = numero;
    }

    @Id

    @Column(name = "idsubfamilia", unique = true, nullable = false)
    public Integer getIdsubfamilia() {
        return this.idsubfamilia;
    }

    public void setIdsubfamilia(Integer idsubfamilia) {
        this.idsubfamilia = idsubfamilia;
    }

    @Column(name = "subfamilia", nullable = false, length = 50)
    public String getSubfamilia() {
        return this.subfamilia;
    }

    public void setSubfamilia(String subfamilia) {
        this.subfamilia = subfamilia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idfamilia", nullable = false)
    public Familia getFamilia() {
        return this.familia;
    }

    public void setFamilia(Familia familia) {
        this.familia = familia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 23)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "numero", length = 2)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idsubfamilia != null)
                ? idsubfamilia.equals(((Subfamilia) other).idsubfamilia)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idsubfamilia != null)
                ? (getClass().hashCode() + idsubfamilia.hashCode())
                : super.hashCode();
    }

}
