package Model;
// Generated 13/08/2015 11:16:31 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tiempopago generated by hbm2java
 */
@Entity
@Table(name="tiempopago"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Tiempopago  implements java.io.Serializable {


     private int idtiempo;
     private String descripcion;
     private Date fecreg;
     private Set ventas = new HashSet(0);

    public Tiempopago() {
    }

	
    public Tiempopago(int idtiempo, String descripcion) {
        this.idtiempo = idtiempo;
        this.descripcion = descripcion;
    }
    public Tiempopago(int idtiempo, String descripcion, Date fecreg, Set ventas) {
       this.idtiempo = idtiempo;
       this.descripcion = descripcion;
       this.fecreg = fecreg;
       this.ventas = ventas;
    }
   
     @Id 

    
    @Column(name="idtiempo", unique=true, nullable=false)
    public int getIdtiempo() {
        return this.idtiempo;
    }
    
    public void setIdtiempo(int idtiempo) {
        this.idtiempo = idtiempo;
    }

    
    @Column(name="descripcion", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecreg", length=23)
    public Date getFecreg() {
        return this.fecreg;
    }
    
    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiempopago")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


