package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "tipodoc", schema = "dbo", catalog = "cobranzas"
)
public class Tipodoc implements java.io.Serializable {

    private Integer idtipodoc;    
    private String tipodoc;
    private String abrev;
    private String serie;
    private String descripcion;
    private Integer correlativo;
    private String tienda;
    private String empresa;

    public Tipodoc() {
    }

    public Tipodoc(Integer idtipodoc) {
        this.idtipodoc = idtipodoc;
    }

    public Tipodoc(Integer idtipodoc, String tipodoc, String abrev, String serie, String descripcion, Integer correlativo, String tienda, String empresa) {
        this.idtipodoc = idtipodoc;        
        this.tipodoc = tipodoc;
        this.abrev = abrev;
        this.serie = serie;
        this.descripcion = descripcion;
        this.correlativo = correlativo;
        this.tienda = tienda;
        this.empresa = empresa;
    }

    @Id

    @Column(name = "idtipodoc", unique = true, nullable = false)
    public Integer getIdtipodoc() {
        return this.idtipodoc;
    }

    public void setIdtipodoc(Integer idtipodoc) {
        this.idtipodoc = idtipodoc;
    }        
    
    @Column(name = "tipodoc", length = 2)
    public String getTipodoc() {
        return this.tipodoc;
    }

    public void setTipodoc(String tipodoc) {
        this.tipodoc = tipodoc;
    }        
    
    @Column(name = "abrev", length = 2)
    public String getAbrev() {
        return abrev;
    }

    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }
    
    @Column(name = "serie", length = 5)
    public String getSerie() {
        return serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }
    
    @Column(name = "descripcion", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name = "correlativo")
    public Integer getCorrelativo() {
        return this.correlativo;
    }

    public void setCorrelativo(Integer correlativo) {
        this.correlativo = correlativo;
    }
    
    @Column(name = "tienda", length = 2)
    public String getTienda() {
        return this.tienda;
    }

    public void setTienda(String tienda) {
        this.tienda = tienda;
    }
    
    @Column(name = "empresa", length = 2)
    public String getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idtipodoc != null)
                ? idtipodoc.equals(((Tipodoc) other).idtipodoc)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idtipodoc != null)
                ? (getClass().hashCode() + idtipodoc.hashCode())
                : super.hashCode();
    }

}

