package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipodocument generated by hbm2java
 */
@Entity
@Table(name="tipodocument"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Tipodocument  implements java.io.Serializable {


     private int idtipodocument;
     private String descripcion;
     private String codigocontable;
     private Set operacions = new HashSet(0);

    public Tipodocument() {
    }

	
    public Tipodocument(int idtipodocument) {
        this.idtipodocument = idtipodocument;
    }
    public Tipodocument(int idtipodocument, String descripcion, String codigocontable, Set operacions) {
       this.idtipodocument = idtipodocument;
       this.descripcion = descripcion;
       this.codigocontable = codigocontable;
       this.operacions = operacions;
    }
   
     @Id 

    
    @Column(name="idtipodocument", unique=true, nullable=false)
    public int getIdtipodocument() {
        return this.idtipodocument;
    }
    
    public void setIdtipodocument(int idtipodocument) {
        this.idtipodocument = idtipodocument;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="codigocontable", length=50)
    public String getCodigocontable() {
        return this.codigocontable;
    }
    
    public void setCodigocontable(String codigocontable) {
        this.codigocontable = codigocontable;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipodocument")
    public Set getOperacions() {
        return this.operacions;
    }
    
    public void setOperacions(Set operacions) {
        this.operacions = operacions;
    }




}


