package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipoventa generated by hbm2java
 */
@Entity
@Table(name="tipoventa"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Tipoventa  implements java.io.Serializable {


     private int idtipoventa;
     private String descripcion;
     private Date created;
     private Set operacions = new HashSet(0);

    public Tipoventa() {
    }

	
    public Tipoventa(int idtipoventa) {
        this.idtipoventa = idtipoventa;
    }
    public Tipoventa(int idtipoventa, String descripcion, Date created, Set operacions) {
       this.idtipoventa = idtipoventa;
       this.descripcion = descripcion;
       this.created = created;
       this.operacions = operacions;
    }
   
     @Id 

    
    @Column(name="idtipoventa", unique=true, nullable=false)
    public int getIdtipoventa() {
        return this.idtipoventa;
    }
    
    public void setIdtipoventa(int idtipoventa) {
        this.idtipoventa = idtipoventa;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoventa")
    public Set getOperacions() {
        return this.operacions;
    }
    
    public void setOperacions(Set operacions) {
        this.operacions = operacions;
    }




}


