package Model;
// Generated 24/07/2015 09:15:20 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoVehiculo generated by hbm2java
 */
public class TipoVehiculo  implements java.io.Serializable {


     private int idtipovehiculo;
     private String nombre;
     private Date fechareg;
     private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

    public TipoVehiculo() {
    }

	
    public TipoVehiculo(int idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }
    public TipoVehiculo(int idtipovehiculo, String nombre, Date fechareg, Set<Vehiculo> vehiculos) {
       this.idtipovehiculo = idtipovehiculo;
       this.nombre = nombre;
       this.fechareg = fechareg;
       this.vehiculos = vehiculos;
    }
   
    public int getIdtipovehiculo() {
        return this.idtipovehiculo;
    }
    
    public void setIdtipovehiculo(int idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }
    public Set<Vehiculo> getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set<Vehiculo> vehiculos) {
        this.vehiculos = vehiculos;
    }




}


