package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipoarticulo generated by hbm2java
 */
@Entity
@Table(name="tipoarticulo"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Tipoarticulo  implements java.io.Serializable {


     private int idtipoarticulo;
     private String descripcion;
     private String abreviado;
     private Date created;
     private Set articulos = new HashSet(0);

    public Tipoarticulo() {
    }

	
    public Tipoarticulo(int idtipoarticulo) {
        this.idtipoarticulo = idtipoarticulo;
    }
    public Tipoarticulo(int idtipoarticulo, String descripcion, String abreviado, Date created, Set articulos) {
       this.idtipoarticulo = idtipoarticulo;
       this.descripcion = descripcion;
       this.abreviado = abreviado;
       this.created = created;
       this.articulos = articulos;
    }
   
     @Id 

    
    @Column(name="idtipoarticulo", unique=true, nullable=false)
    public int getIdtipoarticulo() {
        return this.idtipoarticulo;
    }
    
    public void setIdtipoarticulo(int idtipoarticulo) {
        this.idtipoarticulo = idtipoarticulo;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="abreviado", length=50)
    public String getAbreviado() {
        return this.abreviado;
    }
    
    public void setAbreviado(String abreviado) {
        this.abreviado = abreviado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoarticulo")
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + this.idtipoarticulo;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Tipoarticulo other = (Tipoarticulo) obj;
        if (this.idtipoarticulo != other.idtipoarticulo) {
            return false;
        }
        return true;
    }




}


