package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipoarticulo generated by hbm2java
 */
@Entity
@Table(name="tiposoporte"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Tiposoporte  implements java.io.Serializable {


     private int idtiposoporte;
     private String tiposoporte;
     private Date created;
     private Set soportes = new HashSet(0);

    public Tiposoporte() {
    }
	
    public Tiposoporte(int idtiposoporte) {
        this.idtiposoporte = idtiposoporte;
    }
    
    public Tiposoporte(int idtiposoporte, String tiposoporte, Date created, Set soportes) {
       this.idtiposoporte = idtiposoporte;
       this.tiposoporte = tiposoporte;
       this.created = created;
       this.soportes = soportes;
    }
   
     @Id 

    
    @Column(name="idtiposoporte", unique=true, nullable=false)
    public int getIdtiposoporte() {
        return this.idtiposoporte;
    }
    
    public void setIdtiposoporte(int idtiposoporte) {
        this.idtiposoporte = idtiposoporte;
    }
    
    @Column(name="tiposoporte", length=100)
    public String getTiposoporte() {
        return this.tiposoporte;
    }
    
    public void setTiposoporte(String tiposoporte) {
        this.tiposoporte = tiposoporte;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposoporte")
    public Set getSoportes() {
        return this.soportes;
    }
    
    public void setSoportes(Set soportes) {
        this.soportes = soportes;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + this.idtiposoporte;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Tiposoporte other = (Tiposoporte) obj;
        if (this.idtiposoporte != other.idtiposoporte) {
            return false;
        }
        return true;
    }




}


