package Model;
// Generated 31/07/2015 10:46:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipoanexo generated by hbm2java
 */
@Entity
@Table(name="tipoanexo"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Tipoanexo  implements java.io.Serializable {


     private int idtipoanexo;
     private String nombre;
     private Date fechareg;
     private Set menutipoanexos = new HashSet(0);
     private Set anexos = new HashSet(0);

    public Tipoanexo() {
    }

	
    public Tipoanexo(int idtipoanexo) {
        this.idtipoanexo = idtipoanexo;
    }
    public Tipoanexo(int idtipoanexo, String nombre, Date fechareg, Set menutipoanexos, Set anexos) {
       this.idtipoanexo = idtipoanexo;
       this.nombre = nombre;
       this.fechareg = fechareg;
       this.menutipoanexos = menutipoanexos;
       this.anexos = anexos;
    }
   
     @Id 

    
    @Column(name="idtipoanexo", unique=true, nullable=false)
    public int getIdtipoanexo() {
        return this.idtipoanexo;
    }
    
    public void setIdtipoanexo(int idtipoanexo) {
        this.idtipoanexo = idtipoanexo;
    }

    
    @Column(name="nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechareg", length=23)
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoanexo")
    public Set getMenutipoanexos() {
        return this.menutipoanexos;
    }
    
    public void setMenutipoanexos(Set menutipoanexos) {
        this.menutipoanexos = menutipoanexos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoanexo")
    public Set getAnexos() {
        return this.anexos;
    }
    
    public void setAnexos(Set anexos) {
        this.anexos = anexos;
    }




}


