package Model;
// Generated 27/07/2015 04:12:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Anexo anexo;
     private String usuario;
     private String clave;
     private Date fechareg;

    public Usuario() {
    }

	
    public Usuario(int idusuario, Anexo anexo) {
        this.idusuario = idusuario;
        this.anexo = anexo;
    }
    public Usuario(int idusuario, Anexo anexo, String usuario, String clave, Date fechareg) {
       this.idusuario = idusuario;
       this.anexo = anexo;
       this.usuario = usuario;
       this.clave = clave;
       this.fechareg = fechareg;
    }
   
     @Id 

    
    @Column(name="idusuario", unique=true, nullable=false)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idanexo", nullable=false)
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

    
    @Column(name="usuario", length=20)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="clave", length=20)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechareg", length=23)
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }




}


