package Model;
// Generated Feb 22, 2017 8:23:40 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo",
         schema = "dbo",
         catalog = "cobranzas"
)
public class Vehiculo implements java.io.Serializable {

    private Integer idvehiculo;
    private Color color;
    private Modelo modelo;
    private Character marca;
    private String serie;
    private int anofabri;
    private Date fechareg;
    private String motor;
    private String tipovehiculo;
    private Character estado;
    private Set creditos = new HashSet(0);

    public Vehiculo() {
    }

    public Vehiculo(Integer idvehiculo, Color color, Modelo modelo, String serie, int anofabri) {
        this.idvehiculo = idvehiculo;
        this.color = color;
        this.modelo = modelo;
        this.serie = serie;
        this.anofabri = anofabri;
    }

    public Vehiculo(Integer idvehiculo, Color color, Modelo modelo, Character marca, String serie, int anofabri, Date fechareg, String motor, String tipovehiculo, Character estado, Set creditos) {
        this.idvehiculo = idvehiculo;
        this.color = color;
        this.modelo = modelo;
        this.marca = marca;
        this.serie = serie;
        this.anofabri = anofabri;
        this.fechareg = fechareg;
        this.motor = motor;
        this.tipovehiculo = tipovehiculo;
        this.estado = estado;
        this.creditos = creditos;
    }

    @Id

    @Column(name = "idvehiculo", unique = true, nullable = false)
    public Integer getIdvehiculo() {
        return this.idvehiculo;
    }

    public void setIdvehiculo(Integer idvehiculo) {
        this.idvehiculo = idvehiculo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idcolor", nullable = false)
    public Color getColor() {
        return this.color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idmodelo", nullable = false)
    public Modelo getModelo() {
        return this.modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    @Column(name = "marca", length = 1)
    public Character getMarca() {
        return this.marca;
    }

    public void setMarca(Character marca) {
        this.marca = marca;
    }

    @Column(name = "serie", nullable = false, length = 20)
    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    @Column(name = "anofabri", nullable = false)
    public int getAnofabri() {
        return this.anofabri;
    }

    public void setAnofabri(int anofabri) {
        this.anofabri = anofabri;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechareg", length = 23)
    public Date getFechareg() {
        return this.fechareg;
    }

    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

    @Column(name = "motor", length = 20)
    public String getMotor() {
        return this.motor;
    }

    public void setMotor(String motor) {
        this.motor = motor;
    }

    @Column(name = "tipovehiculo", length = 2)
    public String getTipovehiculo() {
        return this.tipovehiculo;
    }

    public void setTipovehiculo(String tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }

    @Column(name = "estado", length = 1)
    public Character getEstado() {
        return this.estado;
    }

    public void setEstado(Character estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
    public Set getCreditos() {
        return this.creditos;
    }

    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idvehiculo != null)
                ? idvehiculo.equals(((Vehiculo) other).idvehiculo)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idvehiculo != null)
                ? (getClass().hashCode() + idvehiculo.hashCode())
                : super.hashCode();
    }

}
