package Model;
// Generated 24/07/2015 05:48:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Vehiculo  implements java.io.Serializable {


     private int idvehiculo;
     private Tipovehiculo tipovehiculo;
     private String marca;
     private String modelo;
     private String serie;
     private String color;
     private Integer anofabri;
     private Date fechareg;
     private String motor;
     private Integer stock;
     private BigDecimal precio;
     private Set ventas = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(int idvehiculo, Tipovehiculo tipovehiculo) {
        this.idvehiculo = idvehiculo;
        this.tipovehiculo = tipovehiculo;
    }
    public Vehiculo(int idvehiculo, Tipovehiculo tipovehiculo, String marca, String modelo, String serie, String color, Integer anofabri, Date fechareg, String motor, Integer stock, BigDecimal precio, Set ventas) {
       this.idvehiculo = idvehiculo;
       this.tipovehiculo = tipovehiculo;
       this.marca = marca;
       this.modelo = modelo;
       this.serie = serie;
       this.color = color;
       this.anofabri = anofabri;
       this.fechareg = fechareg;
       this.motor = motor;
       this.stock = stock;
       this.precio = precio;
       this.ventas = ventas;
    }
   
     @Id 

    
    @Column(name="idvehiculo", unique=true, nullable=false)
    public int getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(int idvehiculo) {
        this.idvehiculo = idvehiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipovehiculo", nullable=false)
    public Tipovehiculo getTipovehiculo() {
        return this.tipovehiculo;
    }
    
    public void setTipovehiculo(Tipovehiculo tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }

    
    @Column(name="marca", length=20)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="modelo", length=20)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="serie", length=20)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }

    
    @Column(name="color", length=20)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="anofabri")
    public Integer getAnofabri() {
        return this.anofabri;
    }
    
    public void setAnofabri(Integer anofabri) {
        this.anofabri = anofabri;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechareg", length=23)
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

    
    @Column(name="motor", length=20)
    public String getMotor() {
        return this.motor;
    }
    
    public void setMotor(String motor) {
        this.motor = motor;
    }

    
    @Column(name="stock")
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    
    @Column(name="precio", precision=17, scale=4)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


