package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "ventadetalle", schema = "dbo", catalog = "cobranzas"
)
public class Ventadetalle implements java.io.Serializable {

    private Integer idventadetalle;
    private Articulo articulo;

    public Ventadetalle() {
    }

    public Ventadetalle(Integer idventadetalle) {
        this.idventadetalle = idventadetalle;
    }

    public Ventadetalle(Integer idventadetalle, Articulo articulo) {
        this.idventadetalle = idventadetalle;
        this.articulo = articulo;
    }

    @Id

    @Column(name = "idventadetalle", unique = true, nullable = false)
    public Integer getIdventadetalle() {
        return this.idventadetalle;
    }

    public void setIdventadetalle(Integer idventadetalle) {
        this.idventadetalle = idventadetalle;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idarticulo", nullable = false)
    public Articulo getArticulo() {
        return this.articulo;
    }

    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idventadetalle != null)
                ? idventadetalle.equals(((Ventadetalle) other).idventadetalle)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idventadetalle != null)
                ? (getClass().hashCode() + idventadetalle.hashCode())
                : super.hashCode();
    }

}
