package Model;
// Generated 12/08/2015 09:28:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="venta"
    ,schema="dbo"
    ,catalog="cobranzas"
)
public class Venta  implements java.io.Serializable {


     private int idventa;
     private Anexo anexo;
     private Condicionpago condicionpago;
     private Tiempopago tiempopago;
     private Vehiculo vehiculo;
     private Integer idempresa;
     private Date fechareg;
     private String codven;
     private Set datoscreditos = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idventa, Vehiculo vehiculo, String codven) {
        this.idventa = idventa;
        this.vehiculo = vehiculo;
        this.codven = codven;
    }
    public Venta(int idventa, Anexo anexo, Condicionpago condicionpago, Tiempopago tiempopago, Vehiculo vehiculo, Integer idempresa, Date fechareg, String codven, Set datoscreditos) {
       this.idventa = idventa;
       this.anexo = anexo;
       this.condicionpago = condicionpago;
       this.tiempopago = tiempopago;
       this.vehiculo = vehiculo;
       this.idempresa = idempresa;
       this.fechareg = fechareg;
       this.codven = codven;
       this.datoscreditos = datoscreditos;
    }
   
     @Id 

    
    @Column(name="idventa", unique=true, nullable=false)
    public int getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idanexo")
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcondicionpago")
    public Condicionpago getCondicionpago() {
        return this.condicionpago;
    }
    
    public void setCondicionpago(Condicionpago condicionpago) {
        this.condicionpago = condicionpago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtiempo")
    public Tiempopago getTiempopago() {
        return this.tiempopago;
    }
    
    public void setTiempopago(Tiempopago tiempopago) {
        this.tiempopago = tiempopago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="idempresa")
    public Integer getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(Integer idempresa) {
        this.idempresa = idempresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechareg", length=23)
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

    
    @Column(name="codven", nullable=false, length=10)
    public String getCodven() {
        return this.codven;
    }
    
    public void setCodven(String codven) {
        this.codven = codven;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="venta")
    public Set getDatoscreditos() {
        return this.datoscreditos;
    }
    
    public void setDatoscreditos(Set datoscreditos) {
        this.datoscreditos = datoscreditos;
    }




}


