package Model;
// Generated 30/07/2015 11:43:35 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VentaId generated by hbm2java
 */
@Embeddable
public class VentaId  implements java.io.Serializable {


     private int idanexo;
     private int idvehiculo;
     private int idempresa;
     private int idventa;
     private int idpago;

    public VentaId() {
    }

    public VentaId(int idanexo, int idvehiculo, int idempresa, int idventa, int idpago) {
       this.idanexo = idanexo;
       this.idvehiculo = idvehiculo;
       this.idempresa = idempresa;
       this.idventa = idventa;
       this.idpago = idpago;
    }
   


    @Column(name="idanexo", nullable=false)
    public int getIdanexo() {
        return this.idanexo;
    }
    
    public void setIdanexo(int idanexo) {
        this.idanexo = idanexo;
    }


    @Column(name="idvehiculo", nullable=false)
    public int getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(int idvehiculo) {
        this.idvehiculo = idvehiculo;
    }


    @Column(name="idempresa", nullable=false)
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }


    @Column(name="idventa", nullable=false)
    public int getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }


    @Column(name="idpago", nullable=false)
    public int getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(int idpago) {
        this.idpago = idpago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaId) ) return false;
		 VentaId castOther = ( VentaId ) other; 
         
		 return (this.getIdanexo()==castOther.getIdanexo())
 && (this.getIdvehiculo()==castOther.getIdvehiculo())
 && (this.getIdempresa()==castOther.getIdempresa())
 && (this.getIdventa()==castOther.getIdventa())
 && (this.getIdpago()==castOther.getIdpago());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdanexo();
         result = 37 * result + this.getIdvehiculo();
         result = 37 * result + this.getIdempresa();
         result = 37 * result + this.getIdventa();
         result = 37 * result + this.getIdpago();
         return result;
   }   


}


