package Model;
// Generated 22/08/2015 12:24:13 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name = "venta", schema = "dbo", catalog = "cobranzas"
)
public class Venta implements java.io.Serializable {

    private Integer idventa;
    private Anexo anexoByCodven;
    private Anexo anexoByIdanexo;
    private Condicionpago condicionpago;
    private Empresa empresa;
    private Tiempopago tiempopago;
    private Tienda tienda;
    private Vehiculo vehiculo;
    private Date fechareg;
    private String aprobadox;
    private String liqventa;
    private Set datoscreditos = new HashSet(0);

    public Venta() {
    }

    public Venta(Integer idventa, Anexo anexoByIdanexo) {
        this.idventa = idventa;
        this.anexoByIdanexo = anexoByIdanexo;
    }

    public Venta(Integer idventa, Anexo anexoByCodven, Anexo anexoByIdanexo, Condicionpago condicionpago, Empresa empresa, Tiempopago tiempopago, Tienda tienda, Vehiculo vehiculo, Date fechareg, String aprobadox, String liqventa, Set datoscreditos) {
        this.idventa = idventa;
        this.anexoByCodven = anexoByCodven;
        this.anexoByIdanexo = anexoByIdanexo;
        this.condicionpago = condicionpago;
        this.empresa = empresa;
        this.tiempopago = tiempopago;
        this.tienda = tienda;
        this.vehiculo = vehiculo;
        this.fechareg = fechareg;
        this.aprobadox = aprobadox;
        this.liqventa = liqventa;
        this.datoscreditos = datoscreditos;
    }

    @Id

    @Column(name = "idventa", unique = true, nullable = false)
    public Integer getIdventa() {
        return this.idventa;
    }

    public void setIdventa(Integer idventa) {
        this.idventa = idventa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "codven")
    public Anexo getAnexoByCodven() {
        return this.anexoByCodven;
    }

    public void setAnexoByCodven(Anexo anexoByCodven) {
        this.anexoByCodven = anexoByCodven;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idanexo", nullable = false)
    public Anexo getAnexoByIdanexo() {
        return this.anexoByIdanexo;
    }

    public void setAnexoByIdanexo(Anexo anexoByIdanexo) {
        this.anexoByIdanexo = anexoByIdanexo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idcondicionpago")
    public Condicionpago getCondicionpago() {
        return this.condicionpago;
    }

    public void setCondicionpago(Condicionpago condicionpago) {
        this.condicionpago = condicionpago;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idempresa")
    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idtiempo")
    public Tiempopago getTiempopago() {
        return this.tiempopago;
    }

    public void setTiempopago(Tiempopago tiempopago) {
        this.tiempopago = tiempopago;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idtienda")
    public Tienda getTienda() {
        return this.tienda;
    }

    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idvehiculo")
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }

    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechareg", length = 23)
    public Date getFechareg() {
        return this.fechareg;
    }

    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }

    @Column(name = "aprobadox", length = 10)
    public String getAprobadox() {
        return this.aprobadox;
    }

    public void setAprobadox(String aprobadox) {
        this.aprobadox = aprobadox;
    }

    @Column(name = "liqventa", length = 10)
    public String getLiqventa() {
        return this.liqventa;
    }

    public void setLiqventa(String liqventa) {
        this.liqventa = liqventa;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "venta")
    public Set getDatoscreditos() {
        return this.datoscreditos;
    }

    public void setDatoscreditos(Set datoscreditos) {
        this.datoscreditos = datoscreditos;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idventa != null)
                ? idventa.equals(((Venta) other).idventa)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idventa != null)
                ? (getClass().hashCode() + idventa.hashCode())
                : super.hashCode();
    }

}
