package Model;
// Generated 21/04/2016 10:03:10 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "visitas", schema = "dbo", catalog = "cobranzas"
)
public class Visitas implements java.io.Serializable {

    private Integer idvisitas;
    private Creditogestor creditogestor;
    private Date fecreg;
    private String descripcion;
    private Boolean compromiso;
    private Date feccomp;
    private BigDecimal montocomp;
    private String comprobante;
    private String observaciones;
    private String abrev;
    private Integer usuario;

    public Visitas() {
    }

    public Visitas(Integer idvisitas) {
        this.idvisitas = idvisitas;
    }

    public Visitas(Integer idvisitas, Creditogestor creditogestor, String descripcion, Boolean compromiso, Date fecreg, Date feccomp, BigDecimal montocomp,  String comprobante,  String observaciones, String abrev, Integer usuario) {
        this.idvisitas = idvisitas;
        this.creditogestor = creditogestor;
        this.fecreg = fecreg;
        this.descripcion = descripcion;
        this.compromiso =compromiso;
        this.feccomp = feccomp;
        this.montocomp = montocomp;
        this.comprobante = comprobante;
        this.observaciones = observaciones;
        this.abrev = abrev;
        this.usuario = usuario;
    }   

    @Id

    @Column(name = "idvisitas", unique = true, nullable = false)
    public Integer getIdvisitas() {
        return this.idvisitas;
    }

    public void setIdvisitas(Integer idvisitas) {
        this.idvisitas = idvisitas;
    }
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idcreditogestor", nullable = false)
    public Creditogestor getCreditogestor() {
        return this.creditogestor;
    }

    public void setCreditogestor(Creditogestor creditogestor) {
        this.creditogestor = creditogestor;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecreg", nullable = false, length = 23)
    public Date getFecreg() {
        return this.fecreg;
    }

    public void setFecreg(Date fecreg) {
        this.fecreg = fecreg;
    }
    
    @Column(name = "descripcion", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name = "compromiso")
    public Boolean getCompromiso() {
        return this.compromiso;
    }

    public void setCompromiso(Boolean compromiso) {
        this.compromiso = compromiso;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "feccomp", nullable = false, length = 23)
    public Date getFeccomp() {
        return this.feccomp;
    }

    public void setFeccomp(Date feccomp) {
        this.feccomp = feccomp;
    }
    
    @Column(name = "montocomp", nullable = false, precision = 17)
    public BigDecimal getMontocomp() {
        return this.montocomp;
    }

    public void setMontocomp(BigDecimal montocomp) {
        this.montocomp = montocomp;
    }
    
    @Column(name = "comprobante", length = 20)
    public String getComprobante() {
        return this.comprobante;
    }

    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }  
    
    @Column(name = "observaciones", length = 800)
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    
    @Column(name = "abrev", length = 2)
    public String getAbrev() {
        return this.abrev;
    }

    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }
    
    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Override
    public boolean equals(Object other) {
        return (other != null && getClass() == other.getClass() && idvisitas != null)
                ? idvisitas.equals(((Visitas) other).idvisitas)
                : (other == this);
    }

    @Override
    public int hashCode() {
        return (idvisitas != null)
                ? (getClass().hashCode() + idvisitas.hashCode())
                : super.hashCode();
    }

}


