package CRUD.Entidad;
// Generated 23/07/2015 03:57:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="cobranzas"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private int rolIdRol;
     private String usuario;
     private String clave;
     private String email;
     private Boolean estado;
     private String usuariocre;
     private Date fechacre;
     private String usuariomod;
     private Date fechamod;

    public Usuario() {
    }

	
    public Usuario(int rolIdRol) {
        this.rolIdRol = rolIdRol;
    }
    public Usuario(int rolIdRol, String usuario, String clave, String email, Boolean estado, String usuariocre, Date fechacre, String usuariomod, Date fechamod) {
       this.rolIdRol = rolIdRol;
       this.usuario = usuario;
       this.clave = clave;
       this.email = email;
       this.estado = estado;
       this.usuariocre = usuariocre;
       this.fechacre = fechacre;
       this.usuariomod = usuariomod;
       this.fechamod = fechamod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="Rol_idRol", nullable=false)
    public int getRolIdRol() {
        return this.rolIdRol;
    }
    
    public void setRolIdRol(int rolIdRol) {
        this.rolIdRol = rolIdRol;
    }

    
    @Column(name="usuario", length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="clave", length=32)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    
    @Column(name="usuariocre", length=25)
    public String getUsuariocre() {
        return this.usuariocre;
    }
    
    public void setUsuariocre(String usuariocre) {
        this.usuariocre = usuariocre;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechacre", length=19)
    public Date getFechacre() {
        return this.fechacre;
    }
    
    public void setFechacre(Date fechacre) {
        this.fechacre = fechacre;
    }

    
    @Column(name="usuariomod", length=25)
    public String getUsuariomod() {
        return this.usuariomod;
    }
    
    public void setUsuariomod(String usuariomod) {
        this.usuariomod = usuariomod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechamod", length=19)
    public Date getFechamod() {
        return this.fechamod;
    }
    
    public void setFechamod(Date fechamod) {
        this.fechamod = fechamod;
    }




}


